import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { CategoryBadge, Chip } from "@/components/campus-ui";
import { C, shadow } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { activityTranslations, useI18n } from "@/lib/i18n";
import { type Team, useMaintenance } from "@/lib/maintenance-store";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/hooks/use-auth";

const teams: Team[] = ["ICT", "Physical Maintenance", "Security"];
const teamKey: Record<Team, string> = { ICT: "ict", "Physical Maintenance": "physicalMaintenance", Security: "security" };
const stages = ["Submitted", "Assigned", "In Progress", "Resolved"] as const;

export default function RequestDetail() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { width } = useWindowDimensions();
  const { role, requests, assign, status, note, acknowledge, rate, setArrival } = useMaintenance();
  const { isAuthenticated } = useAuth();
  const { language, t } = useI18n();
  const [updateText, setUpdateText] = useState("");
  const [previewVisible, setPreviewVisible] = useState(false);
  const [arrivalText, setArrivalText] = useState("");
  const [assignedTeam, setAssignedTeam] = useState<Team | null>(null);
  const [assigneeUserId, setAssigneeUserId] = useState<number | null>(null);
  const [assignmentError, setAssignmentError] = useState("");
  const [operationError, setOperationError] = useState("");
  const request = requests.find((item) => item.id === id);
  const directory = trpc.campusIdentity.directory.useQuery(undefined, { enabled: isAuthenticated && role === "administrator", retry: false });

  if (!request) return <View style={s.empty}><Text style={s.emptyTitle}>{t("noRequests")}</Text></View>;

  const worker = role === "ict" || role === "maintenance" || role === "security";
  const canAcknowledge = role === "security" && request.team === "Security" && request.priority === "Urgent" && !request.acknowledged;
  const activeStage = Math.max(0, stages.indexOf(request.status as (typeof stages)[number]));
  const stageName = (stage: string) => stage === "In Progress" ? t("inProgress") : stage === "Submitted" ? t("submitted") : stage === "Assigned" ? t("assigned") : t("resolved");
  const saveUpdate = async () => { if (!updateText.trim()) return; try { setOperationError(""); await note(request.id, updateText.trim()); haptic.light(); setUpdateText(""); } catch (cause) { setOperationError(cause instanceof Error ? cause.message : "Unable to post the update."); } };
  const completeAction = async () => { try { setOperationError(""); await status(request.id, request.status === "Assigned" ? "In Progress" : "Resolved", request.status === "Assigned" ? "Technician has begun work." : "Resolution recorded by the assigned team."); haptic.success(); } catch (cause) { setOperationError(cause instanceof Error ? cause.message : "Unable to update this request."); } };
  const saveArrival = async () => { if (!arrivalText.trim()) return; try { setOperationError(""); await setArrival(request.id, arrivalText.trim()); haptic.success(); setArrivalText(""); } catch (cause) { setOperationError(cause instanceof Error ? cause.message : "Unable to save the arrival time."); } };
  const confirmAcknowledgement = async () => { try { setOperationError(""); await acknowledge(request.id); haptic.success(); } catch (cause) { setOperationError(cause instanceof Error ? cause.message : "Unable to acknowledge this incident."); } };
  const saveRating = async (value: 1 | 2 | 3) => { try { setOperationError(""); await rate(request.id, value); haptic.success(); } catch (cause) { setOperationError(cause instanceof Error ? cause.message : "Unable to save this feedback."); } };
  const activeAssignmentTeam = assignedTeam ?? request.team;
  const requiredRole = activeAssignmentTeam === "ICT" ? "ict" : activeAssignmentTeam === "Security" ? "security" : "maintenance";
  const compatibleStaff = directory.data?.filter((account) => account.operationalRole === requiredRole) ?? [];
  const selectedStaff = compatibleStaff.find((account) => account.id === assigneeUserId);
  const saveAssignment = async () => { if (!selectedStaff) { setAssignmentError("Select a registered staff account with the matching operational role."); return; } setAssignmentError(""); try { await assign(request.id, activeAssignmentTeam, { userId: selectedStaff.id, name: selectedStaff.name || selectedStaff.email || "Institution account" }); haptic.success(); setAssigneeUserId(null); } catch (cause) { setAssignmentError(cause instanceof Error ? cause.message : "Unable to assign this request."); } };

  return (
    <View style={s.screen}>
      <ScrollView contentContainerStyle={[s.content, width > 740 && s.wide]} keyboardShouldPersistTaps="handled">
        <View style={s.header}>
          <Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.navy} /></Pressable>
          <View style={{ flex: 1 }}><Text style={s.reference}>{request.id}</Text><Text style={s.context}>{role === "administrator" ? t("administratorView") : t("requestDetail")}</Text></View>
          <Chip value={request.status} />
        </View>

        <View style={s.summaryCard}>
          <View style={s.summaryTop}><View style={s.summaryIcon}><MaterialIcons name="assignment" size={20} color={C.blue} /></View><Chip value={request.priority} /></View>
          <CategoryBadge category={request.category} />
          <Text style={s.title}>{request.title}</Text>
          <Text style={s.description}>{request.description}</Text>
          <View style={s.locationContext}>
            <View style={s.locationIcon}><MaterialIcons name="apartment" size={19} color={C.blue} /></View>
            <View style={{ flex: 1 }}><Text style={s.locationLabel}>CAMPUS LOCATION</Text><Text style={s.locationText}>{request.location}</Text></View>
            <MaterialIcons name="near-me" size={19} color={C.blue} />
          </View>
          {request.attachmentUri && <Pressable style={s.evidence} onPress={() => setPreviewVisible(true)}><Image source={{ uri: request.attachmentUri }} style={s.evidenceImage} /><View style={s.evidenceOverlay}><MaterialIcons name="zoom-in" size={16} color="#FFF" /><Text style={s.evidenceOverlayText}>View photo evidence</Text></View></Pressable>}
          <View style={s.routeRow}><View><Text style={s.routeLabel}>{t("routedTo")}</Text><Text style={s.routeTeam}>{t(teamKey[request.team])}</Text>{request.assignee && <Text style={s.assignee}>{t("assignedTo")} {request.assignee}</Text>}</View><MaterialIcons name={request.team === "ICT" ? "computer" : request.team === "Security" ? "security" : "handyman"} size={25} color={C.blue} /></View>
        </View>
        {operationError ? <View style={s.operationError}><MaterialIcons name="error-outline" size={18} color={C.danger} /><Text style={s.operationErrorText}>{operationError}</Text></View> : null}

        <View style={s.railCard}>
          <View style={s.railHeader}><View><Text style={s.railTitle}>Request progress</Text><Text style={s.railSub}>Current state: {stageName(request.status)}</Text></View><MaterialIcons name="timeline" size={21} color={C.blue} /></View>
          <View style={s.rail}>{stages.map((stage, index) => <View key={stage} style={s.stage}><View style={s.stageTop}><View style={[s.stageDot, index <= activeStage && s.stageComplete, index === activeStage && s.stageActive]}><MaterialIcons name={index < activeStage ? "check" : index === activeStage ? "radio-button-checked" : "circle"} size={index === activeStage ? 12 : 10} color="#FFF" /></View>{index < stages.length - 1 && <View style={[s.stageLine, index < activeStage && s.stageLineComplete]} />}</View><Text style={[s.stageText, index === activeStage && s.stageTextActive]}>{stageName(stage)}</Text></View>)}</View>
        </View>

        {request.status !== "Resolved" && <View style={s.arrivalPanel}><View style={s.arrivalHeading}><View style={s.arrivalIcon}><MaterialIcons name="schedule" size={19} color={C.blue} /></View><View style={{ flex: 1 }}><Text style={s.arrivalTitle}>Technician arrival</Text><Text style={s.arrivalText}>{request.arrivalTime ? `Confirmed service time: ${request.arrivalTime}` : "An assigned technician has not entered an arrival time yet."}</Text></View></View>{worker && <View style={s.arrivalEditor}><TextInput value={arrivalText} onChangeText={setArrivalText} placeholder={request.arrivalTime ?? "Example: Today, 14:30"} placeholderTextColor="#8B97AA" style={s.arrivalInput} returnKeyType="done" /><Pressable onPress={() => void saveArrival()} disabled={!arrivalText.trim()} style={[s.arrivalButton, !arrivalText.trim() && s.arrivalButtonDisabled]}><Text style={s.arrivalButtonText}>{request.arrivalTime ? "Update time" : "Set arrival"}</Text></Pressable></View>}</View>}

        {canAcknowledge && <View style={s.urgentPanel}><View style={s.urgentHeader}><MaterialIcons name="priority-high" size={20} color={C.danger} /><Text style={s.urgentTitle}>{t("urgent")}</Text></View><Text style={s.urgentText}>{t("securityNote")}</Text><Pressable onPress={() => void confirmAcknowledgement()} style={s.urgentAction}><Text style={s.urgentActionText}>{t("acknowledgeIncident")}</Text><MaterialIcons name="verified-user" size={19} color="#FFF" /></Pressable></View>}

        {role === "administrator" && request.status !== "Resolved" && <View style={s.actionPanel}><Text style={s.panelTitle}>Route and assign</Text><Text style={s.panelText}>Select the responsible team, then a registered institutional account with the matching operational role.</Text><View style={s.teamButtons}>{teams.map((team) => <Pressable key={team} onPress={() => { setAssignedTeam(team); setAssigneeUserId(null); setAssignmentError(""); }} style={[s.teamButton, activeAssignmentTeam === team && s.teamButtonActive]}><Text style={[s.teamButtonText, activeAssignmentTeam === team && s.teamButtonTextActive]}>{t(teamKey[team])}</Text></Pressable>)}</View>{directory.isLoading ? <View style={s.assignmentLoading}><Text style={s.panelText}>Loading registered staff…</Text></View> : compatibleStaff.length ? <View style={s.staffChoices}>{compatibleStaff.map((staff) => <Pressable key={staff.id} onPress={() => { setAssigneeUserId(staff.id); setAssignmentError(""); }} style={[s.staffChoice, assigneeUserId === staff.id && s.staffChoiceSelected]}><View style={s.staffAvatar}><Text style={s.staffAvatarText}>{(staff.name || staff.email || "IA").slice(0, 2).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={[s.staffName, assigneeUserId === staff.id && s.staffChoiceTextSelected]}>{staff.name || "Institution account"}</Text><Text style={[s.staffMeta, assigneeUserId === staff.id && s.staffChoiceTextSelected]}>{staff.email ?? "Approved institution account"}</Text></View>{assigneeUserId === staff.id && <MaterialIcons name="check-circle" size={18} color="#FFF" />}</Pressable>)}</View> : <View style={s.assignmentEmpty}><MaterialIcons name="group-off" size={17} color={C.warn} /><Text style={s.assignmentEmptyText}>No registered staff account has the required {activeAssignmentTeam} role. Update staff roles in Operations configuration first.</Text></View>}{assignmentError ? <Text style={s.assignmentError}>{assignmentError}</Text> : null}<Pressable onPress={() => void saveAssignment()} disabled={!selectedStaff} style={[s.assignAction, !selectedStaff && s.assignActionDisabled]}><Text style={s.assignActionText}>Assign selected staff member</Text><MaterialIcons name="person-add-alt-1" size={18} color="#FFF" /></Pressable></View>}

        {worker && request.status !== "Resolved" && <View style={s.actionPanel}><Text style={s.panelTitle}>{t("updateRequest")}</Text><Text style={s.panelText}>{request.status === "Submitted" ? t("waitingAssignment") : request.status === "Assigned" ? t("beginWork") : t("completeWork")}</Text>{request.status !== "Submitted" && <Pressable onPress={() => void completeAction()} style={s.mainAction}><Text style={s.mainActionText}>{request.status === "Assigned" ? t("startWork") : t("resolveRequest")}</Text><MaterialIcons name={request.status === "Assigned" ? "play-arrow" : "task-alt"} size={20} color="#FFF" /></Pressable>}</View>}

        {role === "student" && request.status === "Resolved" && <View style={s.actionPanel}><Text style={s.panelTitle}>{t("rateSolution")}</Text><Text style={s.panelText}>{request.satisfaction ? t("feedbackRecorded") : t("rateIntro")}</Text><View style={s.ratingRow}>{([{ n: 3 as const, icon: "sentiment-very-satisfied", label: t("excellent") }, { n: 2 as const, icon: "sentiment-satisfied", label: t("good") }, { n: 1 as const, icon: "sentiment-dissatisfied", label: t("needsReview") }]).map((item) => <Pressable key={item.n} onPress={() => void saveRating(item.n)} style={[s.rating, request.satisfaction === item.n && s.ratingActive]}><MaterialIcons name={item.icon as keyof typeof MaterialIcons.glyphMap} size={19} color={request.satisfaction === item.n ? "#FFF" : C.blue} /><Text style={[s.ratingText, request.satisfaction === item.n && s.ratingTextActive]}>{item.label}</Text></Pressable>)}</View></View>}

        <View><Text style={s.sectionTitle}>{t("activityTimeline")}</Text><Text style={s.sectionSub}>{t("activityTimelineIntro")}</Text></View>
        <View>{request.activity.map((activity, index) => <View key={activity.id} style={s.activity}><View style={s.activityTrack}><View style={[s.activityDot, index === request.activity.length - 1 && s.activityDotLatest]}><MaterialIcons name="check" size={10} color="#FFF" /></View>{index < request.activity.length - 1 && <View style={s.activityLine} />}</View><View style={s.activityCopy}><View style={s.activityHead}><Text style={s.activityTitle}>{activityTranslations[language][activity.action] ?? activity.action}</Text><Text style={s.activityTime}>{activity.time}</Text></View><Text style={s.activityAuthor}>{activity.author}</Text>{activity.note && <Text style={s.activityNote}>{activity.note}</Text>}</View></View>)}</View>

        {(worker || role === "administrator") && request.status !== "Resolved" && <View style={s.updateBox}><Text style={s.updateTitle}>{t("addUpdate")}</Text><TextInput value={updateText} onChangeText={setUpdateText} style={s.updateInput} placeholder="Share a clear progress update" placeholderTextColor="#8B97AA" multiline textAlignVertical="top" /><Pressable onPress={() => void saveUpdate()} disabled={!updateText.trim()} style={[s.postButton, !updateText.trim() && s.postDisabled]}><Text style={s.postText}>{t("postUpdate")}</Text></Pressable></View>}
      </ScrollView>
      <Modal transparent visible={previewVisible} animationType="fade" onRequestClose={() => setPreviewVisible(false)}><View style={s.modalBackdrop}><View style={s.modalCard}><View style={s.modalHeader}><Text style={s.modalTitle}>Photo evidence</Text><Pressable onPress={() => setPreviewVisible(false)} style={s.close}><MaterialIcons name="close" size={20} color="#FFF" /></Pressable></View>{request.attachmentUri && <Image source={{ uri: request.attachmentUri }} style={s.modalImage} resizeMode="contain" />}</View></View></Modal>
    </View>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 40, gap: 16, maxWidth: 760, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 },
  header: { flexDirection: "row", alignItems: "center", gap: 10 }, back: { height: 42, width: 42, borderRadius: 14, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface, alignItems: "center", justifyContent: "center" }, reference: { color: C.navy, fontSize: 15, fontWeight: "900" }, context: { color: C.muted, fontSize: 11, fontWeight: "700", marginTop: 1 },
  summaryCard: { backgroundColor: C.surface, borderRadius: 22, borderWidth: 1, borderColor: C.border, padding: 18, gap: 12, ...shadow }, summaryTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, summaryIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: C.sky, alignItems: "center", justifyContent: "center" }, title: { color: C.navy, fontSize: 23, lineHeight: 30, fontWeight: "900" }, description: { color: C.text, fontSize: 14, lineHeight: 21 }, operationError: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderRadius: 14, backgroundColor: "#FDECEC", borderWidth: 1, borderColor: "#F6C3BF" }, operationErrorText: { flex: 1, color: C.danger, fontSize: 12, lineHeight: 17, fontWeight: "700" },
  locationContext: { flexDirection: "row", gap: 10, alignItems: "center", padding: 12, borderRadius: 15, backgroundColor: C.sky, borderWidth: 1, borderColor: "#CFE4FC" }, locationIcon: { width: 35, height: 35, borderRadius: 11, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, locationLabel: { color: C.blue, fontSize: 9, letterSpacing: 1, fontWeight: "900" }, locationText: { color: C.navy, fontSize: 12, lineHeight: 17, fontWeight: "800", marginTop: 2 },
  evidence: { position: "relative", borderRadius: 15, overflow: "hidden" }, evidenceImage: { width: "100%", height: 184, backgroundColor: C.sky }, evidenceOverlay: { position: "absolute", bottom: 0, left: 0, right: 0, paddingVertical: 8, backgroundColor: "rgba(8,43,115,0.8)", flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 5 }, evidenceOverlayText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  routeRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 12, borderTopWidth: 1, borderTopColor: C.border }, routeLabel: { color: C.muted, fontSize: 10, letterSpacing: 1, fontWeight: "900" }, routeTeam: { color: C.navy, fontSize: 14, fontWeight: "900", marginTop: 2 }, assignee: { color: C.muted, fontSize: 11, marginTop: 2 },
  railCard: { backgroundColor: C.surface, borderRadius: 20, borderWidth: 1, borderColor: C.border, padding: 15, gap: 14 }, railHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, railTitle: { color: C.navy, fontSize: 15, fontWeight: "900" }, railSub: { color: C.muted, fontSize: 11, marginTop: 2, fontWeight: "700" }, rail: { flexDirection: "row" }, stage: { flex: 1, alignItems: "flex-start" }, stageTop: { flexDirection: "row", alignItems: "center", width: "100%" }, stageDot: { width: 21, height: 21, borderRadius: 11, backgroundColor: "#B9C5D5", alignItems: "center", justifyContent: "center", zIndex: 1 }, stageComplete: { backgroundColor: C.success }, stageActive: { backgroundColor: C.blue }, stageLine: { height: 2, backgroundColor: "#DCE4EF", flex: 1 }, stageLineComplete: { backgroundColor: C.success }, stageText: { color: C.muted, fontSize: 9, lineHeight: 13, fontWeight: "800", marginTop: 6, paddingRight: 4 }, stageTextActive: { color: C.blue },
  arrivalPanel: { backgroundColor: "#F3F8FF", borderRadius: 20, borderWidth: 1, borderColor: "#CFE4FC", padding: 15, gap: 11 }, arrivalHeading: { flexDirection: "row", gap: 10, alignItems: "center" }, arrivalIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, arrivalTitle: { color: C.navy, fontSize: 14, fontWeight: "900" }, arrivalText: { color: "#31547F", fontSize: 12, lineHeight: 17, marginTop: 2 }, arrivalEditor: { flexDirection: "row", gap: 8, alignItems: "center" }, arrivalInput: { flex: 1, minHeight: 43, backgroundColor: "#FFF", borderWidth: 1, borderColor: "#CFE4FC", borderRadius: 12, paddingHorizontal: 11, color: C.text, fontSize: 12 }, arrivalButton: { minHeight: 43, backgroundColor: C.navy, borderRadius: 12, paddingHorizontal: 12, justifyContent: "center" }, arrivalButtonDisabled: { backgroundColor: "#AAB8CC" }, arrivalButtonText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  urgentPanel: { backgroundColor: "#FDECEC", borderColor: "#F6C3BF", borderWidth: 1, borderRadius: 20, padding: 16, gap: 8 }, urgentHeader: { flexDirection: "row", gap: 6, alignItems: "center" }, urgentTitle: { color: C.danger, fontSize: 16, fontWeight: "900" }, urgentText: { color: "#7A271A", fontSize: 12, lineHeight: 18 }, urgentAction: { minHeight: 44, borderRadius: 13, backgroundColor: C.danger, paddingHorizontal: 14, justifyContent: "space-between", alignItems: "center", flexDirection: "row" }, urgentActionText: { color: "#FFF", fontSize: 13, fontWeight: "900" },
  actionPanel: { backgroundColor: C.sky, borderWidth: 1, borderColor: "#CFE4FC", borderRadius: 20, padding: 16, gap: 8 }, panelTitle: { color: C.navy, fontSize: 16, fontWeight: "900" }, panelText: { color: "#31547F", fontSize: 12, lineHeight: 18 }, teamButtons: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 2 }, teamButton: { minHeight: 37, borderRadius: 11, backgroundColor: "#FFF", borderColor: "#CFE4FC", borderWidth: 1, paddingHorizontal: 10, justifyContent: "center" }, teamButtonActive: { backgroundColor: C.navy, borderColor: C.navy }, teamButtonText: { color: C.blue, fontSize: 11, fontWeight: "900" }, teamButtonTextActive: { color: "#FFF" }, assignmentLoading: { paddingVertical: 4 }, staffChoices: { gap: 7, marginTop: 3 }, staffChoice: { minHeight: 55, flexDirection: "row", alignItems: "center", gap: 9, padding: 9, borderRadius: 12, backgroundColor: "#FFF", borderWidth: 1, borderColor: "#CFE4FC" }, staffChoiceSelected: { backgroundColor: C.navy, borderColor: C.navy }, staffAvatar: { width: 32, height: 32, borderRadius: 11, backgroundColor: "#EAF4FF", justifyContent: "center", alignItems: "center" }, staffAvatarText: { color: C.blue, fontSize: 10, fontWeight: "900" }, staffName: { color: C.navy, fontSize: 12, fontWeight: "900" }, staffMeta: { color: C.muted, fontSize: 10, marginTop: 2 }, staffChoiceTextSelected: { color: "#FFF" }, assignmentEmpty: { flexDirection: "row", gap: 7, alignItems: "flex-start", padding: 10, borderRadius: 11, backgroundColor: "#FFF", borderWidth: 1, borderColor: "#F6DEB3" }, assignmentEmptyText: { color: "#7A4B00", fontSize: 11, lineHeight: 16, flex: 1 }, assignmentError: { color: C.danger, fontSize: 11, fontWeight: "800", marginTop: 2 }, assignAction: { minHeight: 43, borderRadius: 12, paddingHorizontal: 13, backgroundColor: C.navy, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 3 }, assignActionDisabled: { backgroundColor: "#AAB8CC" }, assignActionText: { color: "#FFF", fontSize: 12, fontWeight: "900" }, mainAction: { minHeight: 47, borderRadius: 14, paddingHorizontal: 14, backgroundColor: C.navy, flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 3 }, mainActionText: { color: "#FFF", fontSize: 14, fontWeight: "900" },
  ratingRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 3 }, rating: { minHeight: 39, borderWidth: 1, borderColor: "#CFE4FC", backgroundColor: "#FFF", borderRadius: 12, paddingHorizontal: 10, alignItems: "center", flexDirection: "row", gap: 5 }, ratingActive: { backgroundColor: C.navy, borderColor: C.navy }, ratingText: { color: C.blue, fontSize: 11, fontWeight: "900" }, ratingTextActive: { color: "#FFF" },
  sectionTitle: { color: C.navy, fontSize: 18, fontWeight: "900" }, sectionSub: { color: C.muted, fontSize: 12, marginTop: 2 }, activity: { flexDirection: "row", gap: 11, minHeight: 73 }, activityTrack: { width: 21, alignItems: "center" }, activityDot: { width: 19, height: 19, borderRadius: 10, backgroundColor: "#95A2B6", alignItems: "center", justifyContent: "center" }, activityDotLatest: { backgroundColor: C.blue }, activityLine: { width: 2, backgroundColor: "#D9E8FA", flex: 1, marginTop: 4 }, activityCopy: { flex: 1, paddingBottom: 13 }, activityHead: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, activityTitle: { color: C.navy, fontSize: 14, fontWeight: "900", flex: 1 }, activityTime: { color: C.muted, fontSize: 10, fontWeight: "700" }, activityAuthor: { color: C.muted, fontSize: 12, marginTop: 2, fontWeight: "700" }, activityNote: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, borderRadius: 11, padding: 10, color: C.text, fontSize: 12, lineHeight: 18, marginTop: 6 },
  updateBox: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 20, padding: 15, gap: 9 }, updateTitle: { color: C.navy, fontSize: 15, fontWeight: "900" }, updateInput: { minHeight: 75, backgroundColor: C.bg, borderColor: C.border, borderWidth: 1, borderRadius: 12, padding: 11, color: C.text, fontSize: 13 }, postButton: { alignSelf: "flex-start", minHeight: 39, borderRadius: 11, backgroundColor: C.blue, paddingHorizontal: 14, justifyContent: "center" }, postDisabled: { backgroundColor: "#B9C5D5" }, postText: { color: "#FFF", fontSize: 12, fontWeight: "900" },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(4,20,51,0.84)", justifyContent: "center", padding: 20 }, modalCard: { backgroundColor: "#10213F", borderRadius: 22, overflow: "hidden", maxHeight: "88%" }, modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 15 }, modalTitle: { color: "#FFF", fontSize: 16, fontWeight: "900" }, close: { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" }, modalImage: { width: "100%", height: 430, backgroundColor: "#06142D" },
  empty: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: C.bg }, emptyTitle: { color: C.navy, fontSize: 18, fontWeight: "900" },
});
