import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { C } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { type Category, type Priority, useMaintenance } from "@/lib/maintenance-store";

const useRouter = () => useExpoRouter() as any;
const categories: Category[] = ["ICT", "Plumbing", "Electrical", "Building", "Cleaning", "Security"]; const priorities: Priority[] = ["Low", "Medium", "High", "Urgent"];
export default function Report() { const router = useRouter(); const { width } = useWindowDimensions(); const { create } = useMaintenance(); const [category, setCategory] = useState<Category>("ICT"); const [priority, setPriority] = useState<Priority>("Medium"); const [title, setTitle] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState(""); const submit = () => { if (!title.trim() || !location.trim() || !description.trim()) { setError("Please add a title, location, and short description."); return; } haptic.success(); router.replace(`/request/${create({ title, category, location, description, priority })}`); };
 return <View style={s.screen}><ScrollView contentContainerStyle={[s.content, width > 740 && s.wide]} keyboardShouldPersistTaps="handled"><View style={s.top}><Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.navy} /></Pressable><View><Text style={s.eyebrow}>NEW REQUEST</Text><Text style={s.title}>Report an issue</Text></View></View><Text style={s.intro}>Share the essentials and we will route the request to the right campus team.</Text><Label text="What needs attention?" /><TextInput value={title} onChangeText={setTitle} style={s.input} placeholder="Example: Classroom projector is not working" placeholderTextColor="#8B97AA" /><Label text="Issue category" /><View style={s.grid}>{categories.map((v) => <Pressable key={v} onPress={() => { haptic.light(); setCategory(v); }} style={[s.category, category === v && s.selected]}><Text style={[s.categoryText, category === v && s.selectedText]}>{v}</Text></Pressable>)}</View><Label text="Where is the issue?" /><TextInput value={location} onChangeText={setLocation} style={s.input} placeholder="Building, room, or nearby landmark" placeholderTextColor="#8B97AA" /><Label text="Describe what you noticed" /><TextInput value={description} onChangeText={setDescription} style={[s.input, s.textarea]} placeholder="Include what is not working and relevant details." placeholderTextColor="#8B97AA" multiline textAlignVertical="top" /><Label text="How urgent is it?" /><View style={s.priority}>{priorities.map((v) => <Pressable key={v} onPress={() => { haptic.light(); setPriority(v); }} style={[s.priorityButton, priority === v && s.selected]}><Text style={[s.priorityText, priority === v && s.selectedText]}>{v}</Text></Pressable>)}</View>{error ? <View style={s.error}><MaterialIcons name="error-outline" size={17} color={C.danger} /><Text style={s.errorText}>{error}</Text></View> : null}<Pressable onPress={submit} style={s.submit}><Text style={s.submitText}>Submit request</Text><MaterialIcons name="arrow-forward" size={20} color="#FFF" /></Pressable><Text style={s.footer}>Security reports are routed directly to the Security team and highlighted for administrator review.</Text></ScrollView></View>; }
function Label({ text }: { text: string }) { return <Text style={s.label}>{text}</Text>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 38, gap: 11, width: "100%", maxWidth: 720, alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, top: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, justifyContent: "center", alignItems: "center" }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.1, fontWeight: "900" }, title: { color: C.navy, fontSize: 25, lineHeight: 31, fontWeight: "900" }, intro: { color: C.muted, fontSize: 13, lineHeight: 19, marginBottom: 6 }, label: { color: C.navy, fontSize: 13, fontWeight: "900", marginTop: 7 }, input: { minHeight: 53, borderWidth: 1, borderColor: C.border, borderRadius: 15, paddingHorizontal: 14, color: C.text, backgroundColor: C.surface, fontSize: 14 }, textarea: { minHeight: 106, paddingTop: 13, lineHeight: 20 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, category: { minWidth: "30%", flexGrow: 1, minHeight: 43, borderRadius: 12, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface, justifyContent: "center", alignItems: "center", paddingHorizontal: 8 }, selected: { backgroundColor: C.navy, borderColor: C.navy }, categoryText: { color: C.muted, fontSize: 11, fontWeight: "900" }, selectedText: { color: "#FFF" }, priority: { flexDirection: "row", gap: 7 }, priorityButton: { flex: 1, minHeight: 39, borderRadius: 12, justifyContent: "center", alignItems: "center", borderColor: C.border, borderWidth: 1, backgroundColor: C.surface }, priorityText: { color: C.muted, fontSize: 11, fontWeight: "900" }, error: { flexDirection: "row", alignItems: "center", gap: 7, padding: 10, borderRadius: 12, backgroundColor: "#FDECEC" }, errorText: { flex: 1, color: C.danger, fontSize: 12, fontWeight: "700" }, submit: { minHeight: 55, marginTop: 10, paddingHorizontal: 18, borderRadius: 18, backgroundColor: C.navy, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, submitText: { color: "#FFF", fontSize: 15, fontWeight: "900" }, footer: { color: C.muted, textAlign: "center", fontSize: 11, lineHeight: 16, marginTop: 2 } });
