import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Mark } from "@/components/campus-ui";
import { C, shadow } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { roles, type Role, useMaintenance } from "@/lib/maintenance-store";

const useRouter = () => useExpoRouter() as any;
const data: { value: Role; icon: keyof typeof MaterialIcons.glyphMap; color: string }[] = [{ value: "student", icon: "school", color: C.blue }, { value: "ict", icon: "computer", color: "#6941C6" }, { value: "maintenance", icon: "handyman", color: C.warn }, { value: "security", icon: "security", color: C.danger }, { value: "administrator", icon: "admin-panel-settings", color: C.navy }];
export default function RoleSelect() { const router = useRouter(); const { width } = useWindowDimensions(); const { role, setRole } = useMaintenance(); return <View style={s.screen}><FlatList data={data} keyExtractor={(x) => x.value} contentContainerStyle={[s.content, width > 740 && s.wide]} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListHeaderComponent={<><View style={s.top}><Mark /><Pressable style={s.close} onPress={() => router.back()}><MaterialIcons name="close" size={21} color={C.navy} /></Pressable></View><Text style={s.eyebrow}>ROLE PREVIEW</Text><Text style={s.title}>Choose a workspace</Text><Text style={s.sub}>Move between each role to test reporting, assignment, work tracking, security handling, and oversight.</Text></>} ListHeaderComponentStyle={{ marginBottom: 20 }} renderItem={({ item }) => { const selected = item.value === role; const r = roles[item.value]; return <Pressable onPress={() => { haptic.light(); setRole(item.value); router.replace("/"); }} style={[s.card, selected && s.cardOn]}><View style={[s.icon, { backgroundColor: `${item.color}18` }]}><MaterialIcons name={item.icon} size={23} color={item.color} /></View><View style={{ flex: 1 }}><View style={s.cardTitleRow}><Text style={s.cardTitle}>{r.label}</Text>{selected && <Text style={s.active}>ACTIVE</Text>}</View><Text style={s.cardText}>{r.summary}</Text></View><MaterialIcons name="chevron-right" size={22} color={selected ? C.blue : C.muted} /></Pressable>; }} ListFooterComponent={<Text style={s.footer}>Production users will see only the workspace assigned to their approved account.</Text>} /></View>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 34, maxWidth: 760, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }, close: { height: 40, width: 40, borderRadius: 13, backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, justifyContent: "center", alignItems: "center" }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.2, fontWeight: "900", marginBottom: 6 }, title: { color: C.navy, fontSize: 28, lineHeight: 34, fontWeight: "900" }, sub: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 6 }, card: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, borderRadius: 20, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, ...shadow }, cardOn: { borderColor: C.blue, backgroundColor: "#FBFDFF" }, icon: { height: 45, width: 45, borderRadius: 15, justifyContent: "center", alignItems: "center" }, cardTitleRow: { flexDirection: "row", alignItems: "center", gap: 7, flexWrap: "wrap" }, cardTitle: { color: C.navy, fontSize: 15, fontWeight: "900" }, active: { color: C.blue, fontSize: 8, letterSpacing: 0.5, fontWeight: "900", paddingHorizontal: 6, paddingVertical: 3, backgroundColor: C.sky, borderRadius: 5 }, cardText: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, footer: { color: C.muted, textAlign: "center", fontSize: 11, lineHeight: 16, marginTop: 20, paddingHorizontal: 14 } });
