import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { C, shadow } from "@/constants/campus";
import type { Priority, Request, Status } from "@/lib/maintenance-store";

export function Mark() { return <View style={s.mark}><View style={s.logo}><MaterialIcons name="account-balance" size={22} color="#FFF" /><View style={s.tick}><MaterialIcons name="check" size={9} color="#FFF" /></View></View><View><Text style={s.campus}>CAMPUS</Text><Text style={s.maintenance}>MAINTENANCE</Text></View></View>; }
const tone = (v: Status | Priority) => v === "Resolved" ? ["#E7F7EF", C.success] : v === "Urgent" ? ["#FDECEC", C.danger] : v === "High" || v === "Assigned" ? ["#FFF5DE", C.warn] : v === "In Progress" || v === "Medium" ? [C.sky, C.blue] : ["#EEF2F7", C.muted];
export function Chip({ value }: { value: Status | Priority }) { const [bg, color] = tone(value); return <View style={[s.chip, { backgroundColor: bg }]}><Text style={[s.chipText, { color }]}>{value}</Text></View>; }
const icon: Record<Request["category"], keyof typeof MaterialIcons.glyphMap> = { ICT: "computer", Plumbing: "water-drop", Electrical: "bolt", Building: "apartment", Cleaning: "cleaning-services", Security: "security" };
export function Card({ item, onPress }: { item: Request; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.card, pressed && s.pressed]}><View style={s.cardTop}><View style={s.ref}><View style={s.itemIcon}><MaterialIcons name={icon[item.category]} size={18} color={C.blue} /></View><Text style={s.refText}>{item.id}</Text></View><Chip value={item.status} /></View><Text style={s.cardTitle} numberOfLines={2}>{item.title}</Text><View style={s.line}><MaterialIcons name="location-on" size={15} color={C.muted} /><Text style={s.location} numberOfLines={1}>{item.location}</Text></View><View style={s.cardBottom}><Text style={s.team}>{item.team}</Text><Chip value={item.priority} /></View></Pressable>; }
const s = StyleSheet.create({ mark: { flexDirection: "row", gap: 9, alignItems: "center" }, logo: { width: 40, height: 40, borderRadius: 14, backgroundColor: C.navy, justifyContent: "center", alignItems: "center", position: "relative" }, tick: { position: "absolute", right: -3, bottom: -3, backgroundColor: C.blue, borderWidth: 2, borderColor: "#FFF", borderRadius: 8, height: 16, width: 16, justifyContent: "center", alignItems: "center" }, campus: { color: C.navy, fontSize: 13, lineHeight: 14, letterSpacing: 2.1, fontWeight: "900" }, maintenance: { color: C.blue, fontSize: 8, lineHeight: 11, letterSpacing: 1.4, fontWeight: "900" }, chip: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99, alignSelf: "flex-start" }, chipText: { fontSize: 10, lineHeight: 13, fontWeight: "900" }, card: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, borderRadius: 20, padding: 16, gap: 10, ...shadow }, pressed: { opacity: 0.75, transform: [{ scale: 0.99 }] }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, ref: { flexDirection: "row", alignItems: "center", gap: 8 }, itemIcon: { padding: 7, backgroundColor: C.sky, borderRadius: 10 }, refText: { color: C.blue, fontSize: 12, letterSpacing: 0.4, fontWeight: "900" }, cardTitle: { color: C.text, fontSize: 16, lineHeight: 21, fontWeight: "900" }, line: { flexDirection: "row", alignItems: "center", gap: 4 }, location: { color: C.muted, fontSize: 12, flex: 1 }, cardBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 2 }, team: { color: C.muted, fontSize: 12, fontWeight: "800" } });
