import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useRef } from "react";
import { Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { C, shadow } from "@/constants/campus";
import { useI18n } from "@/lib/i18n";
import type { Category, Priority, Request, Status, Team } from "@/lib/maintenance-store";
import { formatSlaDeadline, slaState } from "@/lib/sla";

export function Mark() { return <View style={s.mark}><View style={s.logo}><MaterialIcons name="account-balance" size={22} color="#FFF" /><View style={s.tick}><MaterialIcons name="check" size={9} color="#FFF" /></View></View><View><Text style={s.campus}>CAMPUS</Text><Text style={s.maintenance}>MAINTENANCE</Text></View></View>; }

const valueKey: Record<Status | Priority, string> = { Submitted: "submitted", Assigned: "assigned", "In Progress": "inProgress", Resolved: "resolved", Low: "low", Medium: "medium", High: "high", Urgent: "urgent" };
const categoryKey: Record<Category, string> = { ICT: "ict", Plumbing: "plumbing", Electrical: "electrical", Building: "building", Cleaning: "cleaning", Security: "security" };
const teamKey: Record<Team, string> = { ICT: "ict", "Physical Maintenance": "physicalMaintenance", Security: "security" };
const categoryIcon: Record<Category, keyof typeof MaterialIcons.glyphMap> = { ICT: "computer", Plumbing: "water-drop", Electrical: "bolt", Building: "apartment", Cleaning: "cleaning-services", Security: "security" };

function tone(value: Status | Priority) { return value === "Resolved" ? ["#E7F7EF", C.success] : value === "Urgent" ? ["#FDECEC", C.danger] : value === "High" || value === "Assigned" ? ["#FFF5DE", C.warn] : value === "In Progress" || value === "Medium" ? [C.sky, C.blue] : ["#EEF2F7", C.muted]; }
export function Chip({ value }: { value: Status | Priority }) { const { t } = useI18n(); const [backgroundColor, color] = tone(value); return <View style={[s.chip, { backgroundColor }]}><Text style={[s.chipText, { color }]}>{t(valueKey[value])}</Text></View>; }
export function CategoryBadge({ category }: { category: Category }) { const { t } = useI18n(); return <View style={s.categoryBadge}><MaterialIcons name={categoryIcon[category]} size={14} color={C.blue} /><Text style={s.categoryText}>{t(categoryKey[category])}</Text></View>; }

export function Card({ item, onPress }: { item: Request; onPress: () => void }) {
  const { t } = useI18n(); const entry = useRef(new Animated.Value(0)).current;
  const deadlineState = slaState(item.slaDueAt, item.status); const deadlineAlert = deadlineState === "breached" || deadlineState === "approaching";
  useEffect(() => { Animated.timing(entry, { toValue: 1, duration: 280, useNativeDriver: true }).start(); }, [entry]);
  return <Animated.View style={{ opacity: entry, transform: [{ translateY: entry.interpolate({ inputRange: [0, 1], outputRange: [10, 0] }) }] }}><Pressable onPress={onPress} style={({ pressed }) => [s.card, deadlineAlert && s.cardDeadlineAlert, pressed && s.pressed]} accessibilityRole="button" accessibilityLabel={`${item.id}, ${item.title}`}><View style={[s.accent, { backgroundColor: deadlineAlert ? C.danger : item.priority === "Urgent" ? C.danger : item.category === "ICT" ? C.blue : C.navy }]} /><View style={s.cardTop}><View style={s.ref}><View style={s.itemIcon}><MaterialIcons name={categoryIcon[item.category]} size={18} color={C.blue} /></View><View><Text style={s.refText}>{item.id}</Text><CategoryBadge category={item.category} /></View></View><Chip value={item.status} /></View><Text style={s.cardTitle} numberOfLines={2}>{item.title}</Text><View style={s.line}><MaterialIcons name="location-on" size={15} color={C.muted} /><Text style={s.location} numberOfLines={1}>{item.location}</Text></View>{deadlineState !== "none" && <View style={[s.slaRow, deadlineAlert && s.slaAlert]}><MaterialIcons name={deadlineState === "breached" ? "error-outline" : deadlineState === "approaching" ? "schedule" : "verified"} size={14} color={deadlineAlert ? C.danger : C.success} /><Text style={[s.slaText, deadlineAlert && s.slaTextAlert]}>{deadlineState === "breached" ? `SLA breached · ${formatSlaDeadline(item.slaDueAt)}` : deadlineState === "approaching" ? `SLA deadline approaching · ${formatSlaDeadline(item.slaDueAt)}` : formatSlaDeadline(item.slaDueAt)}</Text></View>}<View style={s.cardBottom}><View style={s.teamWrap}><MaterialIcons name="groups" size={14} color={C.muted} /><Text style={s.team}>{t(teamKey[item.team])}</Text></View><Chip value={item.priority} /></View></Pressable></Animated.View>;
}

const s = StyleSheet.create({ mark: { flexDirection: "row", gap: 9, alignItems: "center" }, logo: { width: 40, height: 40, borderRadius: 14, backgroundColor: C.navy, justifyContent: "center", alignItems: "center", position: "relative" }, tick: { position: "absolute", right: -3, bottom: -3, backgroundColor: C.blue, borderWidth: 2, borderColor: "#FFF", borderRadius: 8, height: 16, width: 16, justifyContent: "center", alignItems: "center" }, campus: { color: C.navy, fontSize: 13, lineHeight: 14, letterSpacing: 2.1, fontWeight: "900" }, maintenance: { color: C.blue, fontSize: 8, lineHeight: 11, letterSpacing: 1.4, fontWeight: "900" }, chip: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99, alignSelf: "flex-start" }, chipText: { fontSize: 10, lineHeight: 13, fontWeight: "900" }, categoryBadge: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 2 }, categoryText: { color: C.muted, fontSize: 10, fontWeight: "800" }, card: { overflow: "hidden", backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, borderRadius: 20, padding: 16, gap: 10, ...shadow }, cardDeadlineAlert: { borderColor: "#F7C9C6", backgroundColor: "#FFFDFD" }, accent: { width: 4, position: "absolute", left: 0, top: 18, bottom: 18, borderTopRightRadius: 4, borderBottomRightRadius: 4 }, pressed: { opacity: 0.76, transform: [{ scale: 0.99 }] }, cardTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, ref: { flexDirection: "row", alignItems: "center", gap: 8 }, itemIcon: { padding: 7, backgroundColor: C.sky, borderRadius: 10 }, refText: { color: C.blue, fontSize: 12, letterSpacing: 0.4, fontWeight: "900" }, cardTitle: { color: C.text, fontSize: 16, lineHeight: 21, fontWeight: "900" }, line: { flexDirection: "row", alignItems: "center", gap: 4 }, location: { color: C.muted, fontSize: 12, flex: 1 }, slaRow: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 9, backgroundColor: "#E7F7EF", paddingHorizontal: 8, paddingVertical: 6 }, slaAlert: { backgroundColor: "#FDECEC", borderWidth: 1, borderColor: "#F7C9C6" }, slaText: { flex: 1, color: C.success, fontSize: 10, lineHeight: 14, fontWeight: "900" }, slaTextAlert: { color: C.danger }, cardBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 2 }, teamWrap: { flexDirection: "row", gap: 4, alignItems: "center", maxWidth: "62%" }, team: { color: C.muted, fontSize: 12, fontWeight: "800" } });
