import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { C, shadow } from "@/constants/campus";
import { useAuth } from "@/hooks/use-auth";
import { useMaintenance } from "@/lib/maintenance-store";
import { trpc } from "@/lib/trpc";

const useRouter = () => useExpoRouter() as any;
type Building = { code: string; name: string; area?: string | null; accessNote?: string | null };

export function GlobalSearch() {
  const router = useRouter(); const { isAuthenticated } = useAuth(); const { role, requests, visible } = useMaintenance(); const buildings = trpc.campusMap.buildings.useQuery(undefined, { enabled: isAuthenticated }); const [query, setQuery] = useState(""); const [focused, setFocused] = useState(false);
  const term = query.trim().toLowerCase(); const allowedRequests = role === "administrator" ? requests : visible;
  const requestMatches = useMemo(() => !term ? [] : allowedRequests.filter((item) => `${item.id} ${item.title} ${item.category} ${item.team} ${item.location}`.toLowerCase().includes(term)).slice(0, 4), [allowedRequests, term]);
  const buildingMatches = useMemo(() => !term ? [] : ((buildings.data ?? []) as Building[]).filter((item) => `${item.code} ${item.name} ${item.area ?? ""}`.toLowerCase().includes(term)).slice(0, 4), [buildings.data, term]);
  const active = focused && term.length > 0; const noResults = active && !buildings.isLoading && requestMatches.length === 0 && buildingMatches.length === 0;
  const close = () => { setFocused(false); setQuery(""); };
  return <View style={s.wrap} pointerEvents="box-none"><View style={s.searchShell}><MaterialIcons name="search" size={19} color={C.blue} /><TextInput value={query} onChangeText={setQuery} onFocus={() => setFocused(true)} placeholder="Search requests, buildings, or teams" placeholderTextColor="#7D8AA2" style={s.input} returnKeyType="search" /><View style={s.hint}><Text style={s.hintText}>⌘ K</Text></View>{query.length > 0 && <Pressable onPress={close} style={s.clear} accessibilityLabel="Clear search"><MaterialIcons name="close" size={17} color={C.muted} /></Pressable>}</View>{active && <View style={s.panel}>{requestMatches.length > 0 && <View style={s.group}><Text style={s.groupLabel}>MAINTENANCE REQUESTS</Text>{requestMatches.map((item) => <Pressable key={item.id} onPress={() => { close(); router.push(`/request/${item.id}`); }} style={({ pressed }) => [s.result, pressed && s.pressed]}><View style={s.resultIcon}><MaterialIcons name="assignment" size={17} color={C.blue} /></View><View style={s.resultCopy}><Text style={s.resultTitle}>{item.title}</Text><Text style={s.resultDetail}>{item.id} · {item.location}</Text></View><Text style={s.resultMeta}>{item.status}</Text></Pressable>)}</View>}{buildingMatches.length > 0 && <View style={s.group}><Text style={s.groupLabel}>VERIFIED CAMPUS BUILDINGS</Text>{buildingMatches.map((item) => <Pressable key={item.code} onPress={() => { close(); router.push(`/building/${item.code}`); }} style={({ pressed }) => [s.result, pressed && s.pressed]}><View style={[s.resultIcon, s.buildingIcon]}><MaterialIcons name="location-city" size={17} color="#6941C6" /></View><View style={s.resultCopy}><Text style={s.resultTitle}>{item.name}</Text><Text style={s.resultDetail}>{item.code}{item.area ? ` · ${item.area}` : ""}</Text></View><MaterialIcons name="arrow-forward" size={18} color={C.muted} /></Pressable>)}</View>}{noResults && <View style={s.empty}><MaterialIcons name="search-off" size={22} color={C.muted} /><View><Text style={s.emptyTitle}>No matching records</Text><Text style={s.emptyText}>{isAuthenticated ? "Try a request reference, building name, team, or location." : "Sign in to include approved campus buildings in search."}</Text></View></View>}{!isAuthenticated && <View style={s.signInNote}><MaterialIcons name="lock-outline" size={15} color={C.blue} /><Text style={s.signInText}>Sign in to search approved campus building records.</Text></View>}</View>}</View>;
}

const s = StyleSheet.create({ wrap: { position: "absolute", left: 350, right: 34, top: 15, zIndex: 80, alignItems: "center" }, searchShell: { height: 46, width: "100%", maxWidth: 610, backgroundColor: "#FFFFFF", borderColor: "#CFE4FC", borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 9, paddingLeft: 14, paddingRight: 8, ...shadow }, input: { flex: 1, color: C.navy, fontSize: 13, fontWeight: "700", outlineStyle: "none" as any }, hint: { borderRadius: 7, backgroundColor: C.bg, paddingHorizontal: 7, paddingVertical: 4 }, hintText: { color: C.muted, fontSize: 10, fontWeight: "900" }, clear: { width: 28, height: 28, alignItems: "center", justifyContent: "center" }, panel: { width: "100%", maxWidth: 610, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: C.border, padding: 8, marginTop: 8, ...shadow }, group: { gap: 2, paddingBottom: 6 }, groupLabel: { color: C.blue, fontSize: 9, letterSpacing: 1, fontWeight: "900", paddingHorizontal: 8, paddingTop: 6, paddingBottom: 4 }, result: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: 10, padding: 8, borderRadius: 11 }, resultIcon: { height: 33, width: 33, borderRadius: 10, backgroundColor: C.sky, alignItems: "center", justifyContent: "center" }, buildingIcon: { backgroundColor: "#F0EAFE" }, resultCopy: { flex: 1 }, resultTitle: { color: C.navy, fontSize: 12, fontWeight: "900" }, resultDetail: { color: C.muted, fontSize: 10, marginTop: 2, fontWeight: "700" }, resultMeta: { color: C.blue, fontSize: 10, fontWeight: "900" }, empty: { minHeight: 70, alignItems: "center", flexDirection: "row", gap: 10, padding: 13 }, emptyTitle: { color: C.navy, fontSize: 12, fontWeight: "900" }, emptyText: { color: C.muted, fontSize: 10, marginTop: 2 }, signInNote: { flexDirection: "row", gap: 6, alignItems: "center", backgroundColor: C.sky, borderRadius: 10, padding: 9, marginTop: 2 }, signInText: { color: "#31547F", fontSize: 10, fontWeight: "700" }, pressed: { backgroundColor: C.bg, opacity: 0.8 } });
