import { desc, eq, inArray } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { campusBuildings, campusEscalationRules, campusSlaPolicies, campusStaffPermissions, campusUserProfiles, InsertMaintenanceRequest, InsertUser, maintenanceRequests, maintenanceUpdates, notificationPreferences, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

export const campusRoles = ["student", "ict", "maintenance", "security", "administrator"] as const;
export type CampusRole = (typeof campusRoles)[number];
export type PreferenceInput = { assignments: boolean; arrivals: boolean; urgent: boolean; resolutions: boolean };
export type OperationalTeamRole = Exclude<CampusRole, "student" | "administrator">;
export type StaffPermissionInput = { manageUsers: boolean; manageRequests: boolean; manageLocations: boolean; manageServiceLevels: boolean; manageEscalations: boolean; viewAnalytics: boolean };
export type EscalationRuleInput = { priority: string; thresholdMinutes: number; notifyRole: CampusRole; active: boolean };
const noPermissions: StaffPermissionInput = { manageUsers: false, manageRequests: false, manageLocations: false, manageServiceLevels: false, manageEscalations: false, viewAnalytics: false };
const allPermissions: StaffPermissionInput = { manageUsers: true, manageRequests: true, manageLocations: true, manageServiceLevels: true, manageEscalations: true, viewAnalytics: true };

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date() }; const updateSet: Record<string, unknown> = { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn }; if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }

export async function getCampusProfile(userId: number, isPlatformAdmin = false) { const db = await getDb(); const defaultRole: CampusRole = isPlatformAdmin ? "administrator" : "student"; if (!db) return { userId, operationalRole: defaultRole, persisted: false }; const rows = await db.select().from(campusUserProfiles).where(eq(campusUserProfiles.userId, userId)).limit(1); if (rows[0]) { if (isPlatformAdmin && rows[0].operationalRole !== "administrator") { await db.update(campusUserProfiles).set({ operationalRole: "administrator" }).where(eq(campusUserProfiles.userId, userId)); return { ...rows[0], operationalRole: "administrator" as CampusRole, persisted: true }; } return { ...rows[0], operationalRole: rows[0].operationalRole as CampusRole, persisted: true }; } await db.insert(campusUserProfiles).values({ userId, operationalRole: defaultRole }); const created = await db.select().from(campusUserProfiles).where(eq(campusUserProfiles.userId, userId)).limit(1); return { ...created[0], operationalRole: defaultRole, persisted: true }; }
export async function setCampusProfileRole(userId: number, operationalRole: CampusRole) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(campusUserProfiles).values({ userId, operationalRole }).onDuplicateKeyUpdate({ set: { operationalRole } }); return getCampusProfile(userId); }
export async function getStaffPermissions(userId: number, isPlatformAdmin = false): Promise<StaffPermissionInput> { if (isPlatformAdmin) return allPermissions; const db = await getDb(); if (!db) return noPermissions; const rows = await db.select().from(campusStaffPermissions).where(eq(campusStaffPermissions.userId, userId)).limit(1); if (!rows[0]) return noPermissions; const { manageUsers, manageRequests, manageLocations, manageServiceLevels, manageEscalations, viewAnalytics } = rows[0]; return { manageUsers, manageRequests, manageLocations, manageServiceLevels, manageEscalations, viewAnalytics }; }
export async function saveStaffPermissions(userId: number, permissions: StaffPermissionInput) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(campusStaffPermissions).values({ userId, ...permissions }).onDuplicateKeyUpdate({ set: permissions }); return getStaffPermissions(userId); }
export async function getCampusAccess(userId: number, isPlatformAdmin = false) { const [profile, permissions] = await Promise.all([getCampusProfile(userId, isPlatformAdmin), getStaffPermissions(userId, isPlatformAdmin)]); return { ...profile, permissions }; }
export async function listInstitutionAccounts() { const db = await getDb(); if (!db) return []; const [accounts, profiles, permissionRows] = await Promise.all([db.select({ id: users.id, name: users.name, email: users.email, platformRole: users.role, lastSignedIn: users.lastSignedIn }).from(users).orderBy(users.name), db.select().from(campusUserProfiles), db.select().from(campusStaffPermissions)]); const rolesByUserId = new Map(profiles.map((profile) => [profile.userId, profile.operationalRole as CampusRole])); const permissionsByUserId = new Map(permissionRows.map((permission) => [permission.userId, { manageUsers: permission.manageUsers, manageRequests: permission.manageRequests, manageLocations: permission.manageLocations, manageServiceLevels: permission.manageServiceLevels, manageEscalations: permission.manageEscalations, viewAnalytics: permission.viewAnalytics }])); return accounts.map((account) => ({ ...account, operationalRole: rolesByUserId.get(account.id) ?? "student" as CampusRole, permissions: account.platformRole === "admin" ? allPermissions : permissionsByUserId.get(account.id) ?? noPermissions })); }

export async function getNotificationPreferences(userId: number): Promise<PreferenceInput> { const db = await getDb(); const defaults: PreferenceInput = { assignments: true, arrivals: true, urgent: true, resolutions: true }; if (!db) return defaults; const rows = await db.select().from(notificationPreferences).where(eq(notificationPreferences.userId, userId)).limit(1); if (rows[0]) return { assignments: rows[0].assignments, arrivals: rows[0].arrivals, urgent: rows[0].urgent, resolutions: rows[0].resolutions }; await db.insert(notificationPreferences).values({ userId, ...defaults }); return defaults; }
export async function saveNotificationPreferences(userId: number, values: PreferenceInput) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(notificationPreferences).values({ userId, ...values }).onDuplicateKeyUpdate({ set: values }); return getNotificationPreferences(userId); }

export async function listCampusBuildings() { const db = await getDb(); if (!db) return []; return db.select().from(campusBuildings).where(eq(campusBuildings.active, true)).orderBy(campusBuildings.name); }
export async function getCampusBuilding(code: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(campusBuildings).where(eq(campusBuildings.code, code)).limit(1); return rows[0]; }
export async function getActiveCampusBuilding(code: string) { const building = await getCampusBuilding(code); return building?.active ? building : undefined; }
export async function saveCampusBuilding(input: { code: string; name: string; area?: string; latitude: string; longitude: string; accessNote?: string; active: boolean }) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(campusBuildings).values(input).onDuplicateKeyUpdate({ set: { name: input.name, area: input.area, latitude: input.latitude, longitude: input.longitude, accessNote: input.accessNote, active: input.active } }); return getCampusBuilding(input.code); }
export async function listSlaPolicies() { const db = await getDb(); if (!db) return []; return db.select().from(campusSlaPolicies).orderBy(campusSlaPolicies.priority); }
export async function getSlaPolicy(priority: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(campusSlaPolicies).where(eq(campusSlaPolicies.priority, priority)).limit(1); return rows[0]; }
export async function saveSlaPolicy(input: { priority: string; targetHours: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(campusSlaPolicies).values(input).onDuplicateKeyUpdate({ set: { targetHours: input.targetHours } }); return getSlaPolicy(input.priority); }
export async function listEscalationRules() { const db = await getDb(); if (!db) return []; return db.select().from(campusEscalationRules).orderBy(campusEscalationRules.priority); }
export async function saveEscalationRule(input: EscalationRuleInput) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(campusEscalationRules).values(input).onDuplicateKeyUpdate({ set: { thresholdMinutes: input.thresholdMinutes, notifyRole: input.notifyRole, active: input.active } }); const rows = await db.select().from(campusEscalationRules).where(eq(campusEscalationRules.priority, input.priority)).limit(1); return rows[0]; }

const teamFor = (category: InsertMaintenanceRequest["category"]) => category === "ICT" ? "ICT" : category === "Security" ? "Security" : "Physical Maintenance" as const;
export async function createRequest(input: Omit<InsertMaintenanceRequest, "reference" | "team" | "slaDueAt">, targetHours: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const slaDueAt = new Date(Date.now() + targetHours * 60 * 60 * 1000); const result = await db.insert(maintenanceRequests).values({ ...input, reference: `TMP-${Date.now()}`, team: teamFor(input.category), slaDueAt }); const insertId = Number((result as unknown as { insertId: number }).insertId); const reference = `CM-${2400 + insertId}`; await db.update(maintenanceRequests).set({ reference }).where(eq(maintenanceRequests.id, insertId)); await db.insert(maintenanceUpdates).values({ requestId: insertId, authorId: input.reporterId, action: input.category === "Security" ? "Security incident submitted" : "Request submitted" }); return { id: insertId, reference, slaDueAt }; }
function accountLabel(account: { id: number; name: string | null; email: string | null } | undefined) { return account?.name?.trim() || account?.email || "Institution account"; }
async function hydrateRequestPeople(rows: (typeof maintenanceRequests.$inferSelect)[]) { const db = await getDb(); if (!db || !rows.length) return rows.map((row) => ({ ...row, reporterName: "Institution account", updates: [] })); const ids = rows.map((row) => row.id); const [updates, accounts] = await Promise.all([db.select().from(maintenanceUpdates).where(inArray(maintenanceUpdates.requestId, ids)).orderBy(desc(maintenanceUpdates.createdAt)), db.select({ id: users.id, name: users.name, email: users.email }).from(users)]); const accountsById = new Map(accounts.map((account) => [account.id, account])); return rows.map((row) => ({ ...row, reporterName: accountLabel(accountsById.get(row.reporterId)), updates: updates.filter((update) => update.requestId === row.id).reverse().map((update) => ({ ...update, authorName: accountLabel(accountsById.get(update.authorId)) })) })); }
export async function listRequests(userId: number, canSeeAll: boolean) { const db = await getDb(); if (!db) return []; const rows = canSeeAll ? await db.select().from(maintenanceRequests).orderBy(desc(maintenanceRequests.updatedAt)) : await db.select().from(maintenanceRequests).where(eq(maintenanceRequests.reporterId, userId)).orderBy(desc(maintenanceRequests.updatedAt)); return hydrateRequestPeople(rows); }
export async function listRequestsForRole(userId: number, role: CampusRole, canSeeAll = false) { const db = await getDb(); if (!db) return []; const rows = canSeeAll || role === "administrator" ? await db.select().from(maintenanceRequests).orderBy(desc(maintenanceRequests.updatedAt)) : role === "student" ? await db.select().from(maintenanceRequests).where(eq(maintenanceRequests.reporterId, userId)).orderBy(desc(maintenanceRequests.updatedAt)) : await db.select().from(maintenanceRequests).where(eq(maintenanceRequests.assigneeUserId, userId)).orderBy(desc(maintenanceRequests.updatedAt)); return hydrateRequestPeople(rows); }
export async function updateRequest(id: number, changes: Partial<InsertMaintenanceRequest>) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(maintenanceRequests).set(changes).where(eq(maintenanceRequests.id, id)); }
export async function addUpdate(requestId: number, authorId: number, action: string, note?: string) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(maintenanceUpdates).values({ requestId, authorId, action, note: note ?? null }); }
export async function getRequest(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(maintenanceRequests).where(eq(maintenanceRequests.id, id)).limit(1); return rows[0]; }
export async function canAccessRequest(requestId: number, userId: number, role: CampusRole, isPlatformAdmin = false) { const request = await getRequest(requestId); if (!request) return { request: undefined, allowed: false }; const allowed = isPlatformAdmin || role === "administrator" || request.reporterId === userId || request.assigneeUserId === userId; return { request, allowed }; }
