import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { C, shadow } from "@/constants/campus";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

export default function BuildingDetail() { const router = useRouter(); const { code } = useLocalSearchParams<{ code: string }>(); const { isAuthenticated } = useAuth(); const building = trpc.campusMap.building.useQuery({ code: code ?? "" }, { enabled: isAuthenticated && Boolean(code) }); const data = building.data as { code: string; name: string; area?: string | null; accessNote?: string | null; latitude?: string | null; longitude?: string | null } | undefined; return <View style={s.screen}><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()} style={({ pressed }) => [s.back, pressed && s.pressed]}><MaterialIcons name="arrow-back" size={21} color={C.navy} /></Pressable>{!isAuthenticated ? <View style={s.empty}><MaterialIcons name="lock-outline" size={32} color={C.blue} /><Text style={s.emptyTitle}>Sign in for verified building details</Text><Text style={s.emptyText}>Approved campus coordinates and access notes are visible only to signed-in users.</Text></View> : building.isLoading ? <View style={s.empty}><Text style={s.emptyText}>Loading building details…</Text></View> : !data ? <View style={s.empty}><MaterialIcons name="location-off" size={32} color={C.muted} /><Text style={s.emptyTitle}>Building not available</Text><Text style={s.emptyText}>The approved campus coordinate data has not been loaded for this building.</Text></View> : <><View style={s.hero}><View style={s.heroIcon}><MaterialIcons name="location-city" size={28} color="#FFF" /></View><Text style={s.eyebrow}>VERIFIED CAMPUS LOCATION</Text><Text style={s.title}>{data.name}</Text><Text style={s.code}>{data.code}{data.area ? ` · ${data.area}` : ""}</Text></View><View style={s.card}><Text style={s.cardLabel}>MAP COORDINATES</Text><Text style={s.coordinate}>{data.latitude}, {data.longitude}</Text><Text style={s.cardText}>This building location is sourced from the approved campus-coordinate register.</Text></View><View style={s.card}><Text style={s.cardLabel}>ACCESS NOTES</Text><Text style={s.cardText}>{data.accessNote || "No additional access note has been recorded."}</Text></View></>}</ScrollView></View>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 24, paddingBottom: 38, width: "100%", maxWidth: 760, alignSelf: "center", gap: 16 }, back: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF", borderWidth: 1, borderColor: C.border }, hero: { backgroundColor: C.navy, borderRadius: 25, padding: 22, gap: 7, overflow: "hidden", ...shadow }, heroIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: C.blue, alignItems: "center", justifyContent: "center", marginBottom: 5 }, eyebrow: { color: "#9ED2FF", fontSize: 10, letterSpacing: 1.1, fontWeight: "900" }, title: { color: "#FFF", fontSize: 26, lineHeight: 31, fontWeight: "900" }, code: { color: "#BBD8FF", fontSize: 13, fontWeight: "700" }, card: { backgroundColor: "#FFF", borderRadius: 20, borderWidth: 1, borderColor: C.border, padding: 17, gap: 6, ...shadow }, cardLabel: { color: C.blue, fontSize: 10, letterSpacing: 1, fontWeight: "900" }, coordinate: { color: C.navy, fontSize: 16, fontWeight: "900" }, cardText: { color: C.muted, fontSize: 12, lineHeight: 18 }, empty: { minHeight: 240, backgroundColor: "#FFF", borderRadius: 22, borderWidth: 1, borderColor: C.border, alignItems: "center", justifyContent: "center", gap: 10, padding: 25 }, emptyTitle: { color: C.navy, fontSize: 17, fontWeight: "900" }, emptyText: { color: C.muted, fontSize: 12, lineHeight: 18, textAlign: "center", maxWidth: 340 }, pressed: { opacity: 0.7 } });
