import { slaState } from "./sla";

export type AnalyticsRequest = { id?: string; title?: string; location?: string; team: "ICT" | "Physical Maintenance" | "Security"; priority: "Low" | "Medium" | "High" | "Urgent"; status: "Submitted" | "Assigned" | "In Progress" | "Resolved"; slaDueAt?: string };

export function computeAdminAnalytics(requests: AnalyticsRequest[]) {
  const total = requests.length; const resolved = requests.filter((item) => item.status === "Resolved").length; const active = requests.filter((item) => item.status === "In Progress").length; const pending = requests.filter((item) => item.status === "Submitted" || item.status === "Assigned").length; const atRisk = requests.filter((item) => item.status !== "Resolved" && (slaState(item.slaDueAt, item.status) === "breached" || slaState(item.slaDueAt, item.status) === "approaching" || (item.priority === "Urgent" && !item.slaDueAt) || (item.priority === "High" && item.status === "Submitted" && !item.slaDueAt))).length; const onTrack = Math.max(0, total - atRisk - pending); const completionRate = total ? Math.round((resolved / total) * 100) : 0;
  const teams = (["ICT", "Physical Maintenance", "Security"] as const).map((team) => { const queue = requests.filter((item) => item.team === team); return { team, total: queue.length, active: queue.filter((item) => item.status === "In Progress").length, resolved: queue.filter((item) => item.status === "Resolved").length, attention: queue.filter((item) => item.status !== "Resolved" && (item.priority === "Urgent" || (item.priority === "High" && item.status === "Submitted"))).length }; });
  return { total, resolved, active, pending, atRisk, onTrack, completionRate, teams };
}

export function analyticsCsv(requests: AnalyticsRequest[], generatedAt = new Date()) {
  const summary = computeAdminAnalytics(requests); const quote = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`; const lines = [["Campus Maintenance Analytics Export"], ["Generated at", generatedAt.toISOString()], [], ["Metric", "Value"], ["Total requests", summary.total], ["Resolved requests", summary.resolved], ["Completion rate", `${summary.completionRate}%`], ["SLA at risk", summary.atRisk], [], ["Team", "Total", "Active", "Resolved", "At risk"], ...summary.teams.map((team) => [team.team, team.total, team.active, team.resolved, team.attention]), [], ["Reference", "Title", "Location", "Team", "Priority", "Status", "SLA due"], ...requests.map((item) => [item.id ?? "", item.title ?? "", item.location ?? "", item.team, item.priority, item.status, item.slaDueAt ?? ""])]; return lines.map((row) => row.map(quote).join(",")).join("\n"); }
