import { createContext, type ReactNode, useContext, useMemo, useState } from "react";

export type Language = "en" | "sn" | "nd";
export type Copy = Record<string, string>;

export const languageOptions: { code: Language; label: string; short: string }[] = [
  { code: "en", label: "English", short: "EN" },
  { code: "sn", label: "Shona", short: "SN" },
  { code: "nd", label: "Ndebele", short: "ND" },
];

export const roleLabelKey = { student: "student", ict: "ictTechnician", maintenance: "maintenanceTechnician", security: "securityOfficer", administrator: "administrator" } as const;
export const roleSummaryKey = { student: "studentSummary", ict: "ictSummary", maintenance: "maintenanceSummary", security: "securitySummary", administrator: "administratorSummary" } as const;

export const activityTranslations: Record<Language, Record<string, string>> = {
  en: { "Request submitted": "Request submitted", "Security incident submitted": "Security incident submitted", "Assigned to ICT": "Assigned to ICT", "Assigned to Physical Maintenance": "Assigned to Physical Maintenance", "Assigned to Security": "Assigned to Security", "Work started": "Work started", Resolved: "Resolved", "Progress update": "Progress update", "Incident acknowledged": "Incident acknowledged", "Resolution feedback received": "Resolution feedback received" },
  sn: { "Request submitted": "Chikumbiro chatumirwa", "Security incident submitted": "Nyaya yechengetedzo yatumirwa", "Assigned to ICT": "Yapihwa ICT", "Assigned to Physical Maintenance": "Yapihwa Kugadzirisa zvivakwa", "Assigned to Security": "Yapihwa Chengetedzo", "Work started": "Basa ratanga", Resolved: "Zvagadziriswa", "Progress update": "Ruzivo rwefambiro", "Incident acknowledged": "Nyaya yabvumwa", "Resolution feedback received": "Ongororo yemhinduro yatambirwa" },
  nd: { "Request submitted": "Isicelo sithunyelwe", "Security incident submitted": "Udaba lwezokuphepha luthunyelwe", "Assigned to ICT": "Kwabelwe ICT", "Assigned to Physical Maintenance": "Kwabelwe ukulungisa izakhiwo", "Assigned to Security": "Kwabelwe ezokuphepha", "Work started": "Umsebenzi usuqalile", Resolved: "Kulungisiwe", "Progress update": "Ulwazi lwenqubekela phambili", "Incident acknowledged": "Udaba seluvunyiwe", "Resolution feedback received": "Impendulo yesixazululo yamukelwe" },
};

export const translations: Record<Language, Copy> = {
  en: {
    home: "Home", requests: "Requests", activity: "Activity", profile: "Profile", language: "Language", english: "English", shona: "Shona", ndebele: "Ndebele",
    demoWorkspace: "DEMONSTRATION WORKSPACE", howHelp: "How can we help today?", readyImpact: "Ready to make an impact?", reportIssue: "Report an issue", reviewRequests: "Review requests", openQueue: "Open work queue",
    openReports: "Open reports", activeWork: "Active work", resolved: "Resolved", needRouting: "Need routing", recentReports: "Your recent reports", recentActivity: "Recent activity", followProgress: "Follow the progress of your requests.", latestVisible: "The latest work visible to your team.", viewAll: "View all",
    commandCenter: "Campus command center", urgentNeeds: "urgent issues need attention across campus.", requestCommand: "Request command center", myRequests: "My requests", myQueue: "My work queue", requestCommandIntro: "Review priorities and route every request to the right team.", myRequestIntro: "Track every issue you have reported.", myQueueIntro: "Open a request to record progress or resolve work.", noRequests: "Nothing in this queue yet.", all: "All", unassigned: "Unassigned",
    newRequest: "NEW REQUEST", reportTitle: "Report an issue", reportIntro: "Share the essentials and we will route the request to the right campus team.", whatNeeds: "What needs attention?", issueCategory: "Issue category", issueLocation: "Where is the issue?", describe: "Describe what you noticed", urgency: "How urgent is it?", submitRequest: "Submit request", missingDetails: "Please add a title, location, and short description.", securityNote: "Security reports are routed directly to the Security team and highlighted for administrator review.",
    requestDetail: "Request detail", administratorView: "Administrator view", routedTo: "ROUTED TO", assignedTo: "Assigned to", routeReassign: "Route or reassign", routeIntro: "Choose the team responsible. Their work queue will update immediately.", updateRequest: "Update this request", startWork: "Start work", resolveRequest: "Resolve request", waitingAssignment: "An administrator must assign this request before work can begin.", beginWork: "Confirm the job is underway for the reporter.", completeWork: "Record the completion when the issue is resolved.", activityTimeline: "Activity timeline", activityTimelineIntro: "Every handoff and update is visible here.", addUpdate: "Add an update", postUpdate: "Post update", acknowledgeIncident: "Acknowledge urgent incident", incidentAcknowledged: "Incident acknowledged", rateSolution: "Rate this solution", rateIntro: "Was the issue resolved satisfactorily?", feedbackRecorded: "Feedback recorded", excellent: "Excellent", good: "Good", needsReview: "Needs review",
    rolePreview: "ROLE PREVIEW", chooseWorkspace: "Choose a workspace", rolePreviewIntro: "Move between each role to test reporting, assignment, work tracking, security handling, and oversight.", active: "ACTIVE", productionNote: "Production users will see only the workspace assigned to their approved account.", switchRole: "Switch demonstration role", notifications: "Notifications", helpSupport: "Help and support", profileDemoNote: "This working MVP uses sample requests and demonstration roles. Secure accounts, live data, and notifications can be enabled next.", workspace: "Workspace",
    student: "Student", ictTechnician: "ICT Technician", maintenanceTechnician: "Physical-Maintenance Technician", securityOfficer: "Security Officer", administrator: "Administrator",
    submitted: "Submitted", assigned: "Assigned", inProgress: "In Progress", low: "Low", medium: "Medium", high: "High", urgent: "Urgent", ict: "ICT", plumbing: "Plumbing", electrical: "Electrical", building: "Building", cleaning: "Cleaning", security: "Security", physicalMaintenance: "Physical Maintenance", studentSummary: "Report campus issues and follow every update.", ictSummary: "Diagnose and resolve technology requests assigned to ICT.", maintenanceSummary: "Handle facilities, plumbing, electrical, and building work.", securitySummary: "Acknowledge, manage, and document safety incidents.", administratorSummary: "Oversee requests, routing, workload, and service quality.", liveAccount: "Live account", connectAccount: "Sign in to save and track requests across devices.", signIn: "Sign in", signOut: "Sign out", savedRequests: "Saved requests",
  },
  sn: {
    home: "Kumba", requests: "Zvikumbiro", activity: "Zviitiko", profile: "Nhoroondo yako", language: "Mutauro", english: "Chirungu", shona: "Shona", ndebele: "Ndebele",
    demoWorkspace: "NZVIMBO YEKUEDZA", howHelp: "Tingakubatsire sei nhasi?", readyImpact: "Wagadzirira kubatsira here?", reportIssue: "Mhan'ara dambudziko", reviewRequests: "Ongorora zvikumbiro", openQueue: "Vhura basa rako",
    openReports: "Mishumo yakavhurika", activeWork: "Basa riripo", resolved: "Zvagadziriswa", needRouting: "Zvinoda kutumirwa", recentReports: "Mishumo yako ichangobva kuitwa", recentActivity: "Zviitiko zvichangobva kuitwa", followProgress: "Tevera mafambiro ezvikumbiro zvako.", latestVisible: "Basa richangobva kuoneka kuchikwata chako.", viewAll: "Ona zvese",
    commandCenter: "Nzvimbo yekutonga kampasi", urgentNeeds: "nyaya dzekukurumidza dzinoda kutariswa pakampasi.", requestCommand: "Kutonga zvikumbiro", myRequests: "Zvikumbiro zvangu", myQueue: "Rondedzero yebasa rangu", requestCommandIntro: "Ongorora kukosha uye tumira chikumbiro kuchikwata chakakodzera.", myRequestIntro: "Tevera dambudziko rega rega rawakamhan'ara.", myQueueIntro: "Vhura chikumbiro kuti unyore mafambiro kana kupedza basa.", noRequests: "Hapana chikumbiro parondedzero iyi.", all: "Zvese", unassigned: "Zvisina kupihwa",
    newRequest: "CHIKUMBIRWA CHITSVA", reportTitle: "Mhan'ara dambudziko", reportIntro: "Tipei ruzivo rwakakosha uye tichatumira chikumbiro kuchikwata chakakodzera.", whatNeeds: "Chii chinoda kugadziriswa?", issueCategory: "Rudzi rwedambudziko", issueLocation: "Dambudziko riri kupi?", describe: "Tsanangura zvawaona", urgency: "Zvinokurumidza zvakadii?", submitRequest: "Tumira chikumbiro", missingDetails: "Nyora musoro, nzvimbo, uye tsananguro pfupi.", securityNote: "Mishumo yechengetedzo inoenda kuchikwata cheChengetedzo uye inoratidzwa kumutungamiri.",
    requestDetail: "Ruzivo rwechikumbiro", administratorView: "Maonero emutungamiri", routedTo: "YATUMIRWA KU", assignedTo: "Yapihwa kuna", routeReassign: "Tumira kana chinja", routeIntro: "Sarudza chikwata chine basa. Rondedzero yebasa ravo ichagadziridzwa pakarepo.", updateRequest: "Gadziridza chikumbiro", startWork: "Tanga basa", resolveRequest: "Pedzisa chikumbiro", waitingAssignment: "Mutungamiri anofanira kupa chikumbiro ichi asati atanga basa.", beginWork: "Simbisa kuti basa ratanga kuti akamhan'ara atevere mafambiro.", completeWork: "Nyora kupedzwa kana dambudziko ragadziriswa.", activityTimeline: "Nhoroondo yezviitiko", activityTimelineIntro: "Kuchinjana kwese neruzivo zvinoratidzwa pano.", addUpdate: "Wedzera ruzivo", postUpdate: "Tumira ruzivo", acknowledgeIncident: "Bvuma nyaya yekukurumidza", incidentAcknowledged: "Nyaya yabvumwa", rateSolution: "Ongorora mhinduro", rateIntro: "Dambudziko ragadziriswa zvinogutsa here?", feedbackRecorded: "Ongororo yanyorwa", excellent: "Zvakanaka zvikuru", good: "Zvakanaka", needsReview: "Zvinoda kuongororwa",
    rolePreview: "KUEDZA MABASA", chooseWorkspace: "Sarudza nzvimbo yebasa", rolePreviewIntro: "Famba pakati pemabasa kuti uedze kumhan'ara, kugovera, kutevera basa, chengetedzo, nekutungamirira.", active: "RIRI KUSHANDA", productionNote: "Vashandisi vekugadzira vachaona chete nzvimbo yebasa yavakapiwa.", switchRole: "Chinja basa rekuyedza", notifications: "Zviziviso", helpSupport: "Rubatsiro nerutsigiro", profileDemoNote: "MVP iyi inoshandisa mienzaniso yezvikumbiro nemabasa ekuyedza. Maakaundi akachengeteka uye data chairo zvinogona kuwedzerwa.", workspace: "Nzvimbo yebasa",
    student: "Mudzidzi", ictTechnician: "Nyanzvi yeICT", maintenanceTechnician: "Nyanzvi yezvivakwa", securityOfficer: "Muchengeti", administrator: "Mutungamiri",
    submitted: "Yatumirwa", assigned: "Yapihwa", inProgress: "Iri kugadziriswa", low: "Shoma", medium: "Pakati", high: "Pamusoro", urgent: "Nekukurumidza", ict: "ICT", plumbing: "Mapombi", electrical: "Magetsi", building: "Zvivakwa", cleaning: "Kuchenesa", security: "Chengetedzo", physicalMaintenance: "Kugadzirisa zvivakwa", studentSummary: "Mhan'ara matambudziko ekampasi uye tevera ruzivo rwese.", ictSummary: "Ongorora uye gadzirisa zvikumbiro zvetekinoroji zvakapiwa ICT.", maintenanceSummary: "Gadzirisa zvivakwa, mapombi, magetsi, nezvimwe zvechivako.", securitySummary: "Bvuma, gadzirisa, uye nyora nyaya dzechengetedzo.", administratorSummary: "Tungamira zvikumbiro, kutumira, basa, uye mhando yebasa.", liveAccount: "Akaunti yepamhepo", connectAccount: "Pinda kuti uchengete uye utevere zvikumbiro pamidziyo yose.", signIn: "Pinda", signOut: "Buda", savedRequests: "Zvikumbiro zvakachengetwa",
  },
  nd: {
    home: "Ekhaya", requests: "Izicelo", activity: "Okwenzekayo", profile: "Iphrofayili", language: "Ulimi", english: "English", shona: "Shona", ndebele: "Ndebele",
    demoWorkspace: "INDAWO YOKUHLOLA", howHelp: "Singakunceda njani lamuhla?", readyImpact: "Usukulungele ukunceda?", reportIssue: "Bika uhlupho", reviewRequests: "Hlola izicelo", openQueue: "Vula uluhlu lomsebenzi",
    openReports: "Imibiko evulekileyo", activeWork: "Umsebenzi osebenzayo", resolved: "Kulungisiwe", needRouting: "Kudinga ukwabelwa", recentReports: "Imibiko yakho esanda kwenziwa", recentActivity: "Okwenzekayo kutsha", followProgress: "Landela inqubekela phambili yezicelo zakho.", latestVisible: "Umsebenzi osanda kubonakala eqenjini lakho.", viewAll: "Bona konke",
    commandCenter: "Isikhungo sokulawula ikhempasi", urgentNeeds: "izindaba eziphuthumayo zidinga ukunakwa ekhempasini.", requestCommand: "Ukulawula izicelo", myRequests: "Izicelo zami", myQueue: "Uluhlu lwami lomsebenzi", requestCommandIntro: "Hlola okubalulekileyo njalo wabele isicelo eqenjini elifaneleyo.", myRequestIntro: "Landela uhlupho ngalunye olubikileyo.", myQueueIntro: "Vula isicelo ukuze ubhale inqubekela phambili kumbe uqede umsebenzi.", noRequests: "Akula sicelo kuloluhlu okwamanje.", all: "Konke", unassigned: "Okungakabelwa",
    newRequest: "ISICELO ESITSHA", reportTitle: "Bika uhlupho", reportIntro: "Yabelana ngolwazi oluqakathekileyo njalo sizathumela isicelo eqenjini elifaneleyo.", whatNeeds: "Kuyini okudinga ukunakwa?", issueCategory: "Uhlobo lohlupho", issueLocation: "Uhlupho lukuphi?", describe: "Chaza okubonileyo", urgency: "Kuyaphuthuma kangakanani?", submitRequest: "Thumela isicelo", missingDetails: "Faka isihloko, indawo, kanye lencazelo emfutshane.", securityNote: "Imibiko yezokuphepha ithunyelwa eqenjini leZokuphepha njalo iyaboniswa kumphathi.",
    requestDetail: "Imininingwane yesicelo", administratorView: "Ukubona komphathi", routedTo: "KUTHUNYELWE KU", assignedTo: "Kwabelwe", routeReassign: "Yabela kumbe tshintsha", routeIntro: "Khetha iqembu elizaphatha. Uluhlu lomsebenzi walo luzabuyekezwa masinyane.", updateRequest: "Buyekeza isicelo", startWork: "Qala umsebenzi", resolveRequest: "Qedisa isicelo", waitingAssignment: "Umphathi kumele aqale abele isicelo lesi kungakaqalwa umsebenzi.", beginWork: "Qinisekisa ukuthi umsebenzi usuqalile ukuze obikileyo alandele inqubekela phambili.", completeWork: "Bhala ukuphela komsebenzi nxa uhlupho selulungisiwe.", activityTimeline: "Umlando wokwenzekayo", activityTimelineIntro: "Ukudlulisela lolwazi lonke kubonakala lapha.", addUpdate: "Engeza ulwazi", postUpdate: "Thumela ulwazi", acknowledgeIncident: "Vuma udaba oluphuthumayo", incidentAcknowledged: "Udaba seluvunyiwe", rateSolution: "Linganisa isixazululo", rateIntro: "Uhlupho lulungiswe ngokwenelisayo na?", feedbackRecorded: "Impendulo igciniwe", excellent: "Kuhle kakhulu", good: "Kuhle", needsReview: "Kudinga ukuhlolwa",
    rolePreview: "UKUHLOLA INDIMA", chooseWorkspace: "Khetha indawo yomsebenzi", rolePreviewIntro: "Hamba phakathi kwendima ukuze uhlole ukubika, ukwabela, ukulandelela umsebenzi, ezokuphepha, lokuphatha.", active: "KUYASEBENZA", productionNote: "Abasebenzisi bangempela bazabona kuphela indawo yomsebenzi abayabelweyo.", switchRole: "Tshintsha indima yokuhlola", notifications: "Izaziso", helpSupport: "Usizo lokusekelwa", profileDemoNote: "Le MVP isebenzisa izicelo zesibonelo lezindima zokuhlola. Ama-akhawunti avikelekileyo ledatha ephilayo kungengezwa.", workspace: "Indawo yomsebenzi",
    student: "Umfundi", ictTechnician: "Uchwepheshe we-ICT", maintenanceTechnician: "Uchwepheshe wokulungisa", securityOfficer: "Isiphathamandla sezokuphepha", administrator: "Umphathi",
    submitted: "Kuthunyelwe", assigned: "Kwabelwe", inProgress: "Kuyalungiswa", low: "Phansi", medium: "Phakathi", high: "Phezulu", urgent: "Kuyaphuthuma", ict: "ICT", plumbing: "Amaphayiphi", electrical: "Ugesi", building: "Izakhiwo", cleaning: "Ukuhlanza", security: "Ezokuphepha", physicalMaintenance: "Ukulungisa izakhiwo", studentSummary: "Bika uhlupho lwekhempasi njalo landela izibuyekezo zonke.", ictSummary: "Hlola njalo ulungise izicelo zobuchwepheshe ezabelwe ICT.", maintenanceSummary: "Phatha izakhiwo, amaphayiphi, ugesi, lomsebenzi wezakhiwo.", securitySummary: "Vuma, phatha, njalo ubhale udaba lwezokuphepha.", administratorSummary: "Bona izicelo, ukwabela, umthwalo womsebenzi, kanye lekhwalithi yesevisi.", liveAccount: "I-akhawunti ephilayo", connectAccount: "Ngena ukuze ugcine njalo ulandele izicelo kumadivayisi wonke.", signIn: "Ngena", signOut: "Phuma", savedRequests: "Izicelo ezigciniweyo",
  },
};

type I18nState = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string };
const I18nContext = createContext<I18nState | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => translations[language][key] ?? translations.en[key] ?? key }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used inside I18nProvider");
  return context;
}
