import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";
import { campusRoles, campusTeamFor } from "@/lib/campus-domain";
import { createSlaDueAt } from "@/lib/sla";

export type Role = "student" | "ict" | "maintenance" | "security" | "administrator";
export type Team = "ICT" | "Physical Maintenance" | "Security";
export type Category = "ICT" | "Plumbing" | "Electrical" | "Building" | "Cleaning" | "Security";
export type Status = "Submitted" | "Assigned" | "In Progress" | "Resolved";
export type Priority = "Low" | "Medium" | "High" | "Urgent";
export type Activity = { id: string; action: string; author: string; time: string; note?: string };
export type Request = { id: string; serverId?: number; title: string; category: Category; location: string; description: string; priority: Priority; status: Status; reporter: string; team: Team; assignee?: string; time: string; activity: Activity[]; acknowledged?: boolean; satisfaction?: 1 | 2 | 3; attachmentUri?: string; arrivalTime?: string; slaDueAt?: string };

export const roles: Record<Role, { label: string; summary: string; initials: string; team?: Team; name: string }> = campusRoles;

const seed: Request[] = [
  { id: "CM-2418", title: "Wi-Fi unavailable in Computer Lab 2", category: "ICT", location: "Technology Block · Computer Lab 2", description: "The classroom network is unavailable on all student workstations.", priority: "High", status: "Assigned", reporter: "Amara N.", team: "ICT", assignee: "Jordan M.", arrivalTime: "Today, 10:15", slaDueAt: new Date(Date.now() + 35 * 60 * 1000).toISOString(), time: "Today, 09:10", activity: [{ id: "1", action: "Request submitted", author: "Amara N.", time: "Today, 08:34" }, { id: "2", action: "Assigned to ICT", author: "Campus Admin", time: "Today, 09:10", note: "Assigned to Jordan M." }, { id: "2a", action: "Technician arrival updated", author: "Jordan M.", time: "Today, 09:14", note: "Expected arrival: Today, 10:15." }] },
  { id: "CM-2417", title: "Leaking tap in residence bathroom", category: "Plumbing", location: "Maple Residence · Room 106", description: "The basin tap continues to drip and the floor is becoming wet.", priority: "Medium", status: "In Progress", reporter: "Amara N.", team: "Physical Maintenance", assignee: "Thabo K.", arrivalTime: "Today, 11:30", time: "Today, 08:50", activity: [{ id: "3", action: "Request submitted", author: "Amara N.", time: "Yesterday, 16:18" }, { id: "4", action: "Work started", author: "Thabo K.", time: "Today, 08:50", note: "Replacement washer is being fitted." }, { id: "4a", action: "Technician arrival updated", author: "Thabo K.", time: "Today, 08:54", note: "Expected completion: Today, 11:30." }] },
  { id: "CM-2416", title: "Exterior light not working near library", category: "Electrical", location: "Central Library · South walkway", description: "The walkway light nearest the east entrance has been off since last night.", priority: "High", status: "Submitted", reporter: "Lebo R.", team: "Physical Maintenance", slaDueAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(), time: "Today, 07:55", activity: [{ id: "5", action: "Request submitted", author: "Lebo R.", time: "Today, 07:55" }] },
  { id: "CM-2415", title: "Unsecured access door after hours", category: "Security", location: "Science Block · Rear entrance", description: "Rear access door was found open after the building closed.", priority: "Urgent", status: "Assigned", reporter: "Facilities Desk", team: "Security", assignee: "Nandi S.", time: "Today, 06:46", activity: [{ id: "6", action: "Security incident submitted", author: "Facilities Desk", time: "Today, 06:42" }, { id: "7", action: "Assigned to Security", author: "Campus Admin", time: "Today, 06:46", note: "High-priority attendance requested." }] },
  { id: "CM-2414", title: "Projector cable replaced", category: "ICT", location: "Humanities Block · Lecture Hall 3", description: "The HDMI connection was damaged and has been replaced.", priority: "Low", status: "Resolved", reporter: "Professor Daniels", team: "ICT", assignee: "Jordan M.", time: "Yesterday, 11:20", activity: [{ id: "8", action: "Resolved", author: "Jordan M.", time: "Yesterday, 11:20", note: "New HDMI cable tested successfully." }] },
];

type Store = { role: Role; setRole: (v: Role) => void; requests: Request[]; visible: Request[]; isLiveData: boolean; create: (v: Pick<Request, "title" | "category" | "location" | "description" | "priority"> & { attachmentUri?: string }, saved?: { id: number; reference: string }) => string; assign: (id: string, team: Team) => void; status: (id: string, value: Status, note?: string) => void; note: (id: string, text: string) => void; acknowledge: (id: string) => void; rate: (id: string, value: 1 | 2 | 3) => void; setArrival: (id: string, value: string) => void };
const Context = createContext<Store | null>(null);
export const teamFor = (category: Category): Team => campusTeamFor(category);
const timeLabel = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleString() : "Recently";
const serverRequest = (item: any): Request => ({ id: item.reference, serverId: item.id, title: item.title, category: item.category, location: item.location, description: item.description, priority: item.priority, status: item.status, reporter: "Account holder", team: item.team, assignee: item.assigneeName ?? undefined, time: timeLabel(item.updatedAt ?? item.createdAt), activity: (item.updates ?? []).map((update: any) => ({ id: String(update.id), action: update.action, author: "Service desk", time: timeLabel(update.createdAt), note: update.note ?? undefined })), acknowledged: item.acknowledged, satisfaction: item.satisfaction ?? undefined, attachmentUri: item.attachmentUrl ?? undefined, arrivalTime: item.arrivalTime ?? undefined, slaDueAt: item.slaDueAt ? new Date(item.slaDueAt).toISOString() : undefined });

export function MaintenanceProvider({ children }: { children: ReactNode }) {
  const [role, setRole] = useState<Role>("student"); const [requests, setRequests] = useState(seed); const { isAuthenticated } = useAuth(); const profile = trpc.campusIdentity.profile.useQuery(undefined, { enabled: isAuthenticated }); const liveRequests = trpc.maintenance.list.useQuery(undefined, { enabled: isAuthenticated, retry: false }); const liveUpdate = trpc.maintenance.addUpdate.useMutation(); const liveAssign = trpc.maintenance.assign.useMutation(); const liveArrival = trpc.maintenance.setArrival.useMutation(); const liveAcknowledge = trpc.maintenance.acknowledge.useMutation(); const liveRating = trpc.maintenance.rate.useMutation();
  useEffect(() => { const value = profile.data?.operationalRole; if (value && value in roles) setRole(value as Role); }, [profile.data?.operationalRole]);
  useEffect(() => { if (isAuthenticated && liveRequests.data) setRequests(liveRequests.data.map(serverRequest)); if (!isAuthenticated) setRequests(seed); }, [isAuthenticated, liveRequests.data]);
  const actor = () => roles[role].name; const patch = (id: string, f: (r: Request) => Request) => setRequests((all) => all.map((r) => r.id === id ? f(r) : r));
  const sync = () => { void liveRequests.refetch(); };
  const create: Store["create"] = (v, saved) => { const id = saved?.reference ?? `CM-${2420 + requests.length}`; const entry: Request = { ...v, id, serverId: saved?.id, status: "Submitted", reporter: actor(), team: teamFor(v.category), slaDueAt: createSlaDueAt(v.priority), time: "Just now", activity: [{ id: `${id}-new`, action: "Request submitted", author: actor(), time: "Just now" }] }; setRequests((all) => [entry, ...all]); return id; };
  const assign: Store["assign"] = (id, team) => { const assignee = team === "ICT" ? "Jordan M." : team === "Security" ? "Nandi S." : "Thabo K."; const request = requests.find((item) => item.id === id); if (isAuthenticated && request?.serverId) void liveAssign.mutateAsync({ id: request.serverId, team, assigneeName: assignee }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, team, assignee, status: "Assigned", time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action: `Assigned to ${team}`, author: "Campus Admin", time: "Just now", note: `Assigned to ${assignee}.` }] })); };
  const status: Store["status"] = (id, value, noteValue) => { const request = requests.find((item) => item.id === id); const action = value === "In Progress" ? "Work started" : value === "Resolved" ? "Resolved" : `Status changed to ${value}`; if (isAuthenticated && request?.serverId) void liveUpdate.mutateAsync({ id: request.serverId, action, note: noteValue, status: value }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, status: value, time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action, author: actor(), time: "Just now", note: noteValue }] })); };
  const note: Store["note"] = (id, text) => { const request = requests.find((item) => item.id === id); if (isAuthenticated && request?.serverId) void liveUpdate.mutateAsync({ id: request.serverId, action: "Progress update", note: text }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action: "Progress update", author: actor(), time: "Just now", note: text }] })); };
  const acknowledge: Store["acknowledge"] = (id) => { const request = requests.find((item) => item.id === id); if (isAuthenticated && request?.serverId) void liveAcknowledge.mutateAsync({ id: request.serverId }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, acknowledged: true, time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action: "Incident acknowledged", author: actor(), time: "Just now", note: "Security officer has acknowledged the urgent incident." }] })); };
  const rate: Store["rate"] = (id, value) => { const request = requests.find((item) => item.id === id); if (isAuthenticated && request?.serverId) void liveRating.mutateAsync({ id: request.serverId, satisfaction: value }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, satisfaction: value, time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action: "Resolution feedback received", author: actor(), time: "Just now", note: value === 3 ? "Reporter marked the resolution excellent." : value === 2 ? "Reporter marked the resolution good." : "Reporter requested a further review." }] })); };
  const setArrival: Store["setArrival"] = (id, value) => { const request = requests.find((item) => item.id === id); if (isAuthenticated && request?.serverId) void liveArrival.mutateAsync({ id: request.serverId, arrivalTime: value }).then(sync).catch(console.warn); patch(id, (r) => ({ ...r, arrivalTime: value, time: "Just now", activity: [...r.activity, { id: `${id}-${Date.now()}`, action: "Technician arrival updated", author: actor(), time: "Just now", note: `Technician-entered arrival time: ${value}.` }] })); };
  const visible = useMemo(() => role === "administrator" ? requests : role === "student" ? requests.filter((r) => r.reporter === "Amara N.") : requests.filter((r) => r.team === roles[role].team), [requests, role]);
  return <Context.Provider value={{ role, setRole, requests, visible, isLiveData: isAuthenticated && Boolean(liveRequests.data), create, assign, status, note, acknowledge, rate, setArrival }}>{children}</Context.Provider>;
}
export const useMaintenance = () => { const value = useContext(Context); if (!value) throw new Error("MaintenanceProvider is missing"); return value; };
