import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Card } from "@/components/campus-ui";
import { ServiceHeader } from "@/components/service-header";
import { C, shadow } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { roleSummaryKey, useI18n } from "@/lib/i18n";
import { useMaintenance } from "@/lib/maintenance-store";

export default function Home() {
  const router = useRouter();
  const { role, visible } = useMaintenance();
  const { t } = useI18n();
  const { width } = useWindowDimensions();
  const student = role === "student";
  const ict = role === "ict";
  const security = role === "security";
  const open = visible.filter((item) => item.status !== "Resolved");
  const active = visible.filter((item) => item.status === "In Progress");
  const waiting = visible.filter((item) => item.status === "Submitted");
  const urgent = visible.filter((item) => item.priority === "Urgent" && item.status !== "Resolved");
  const unacknowledged = urgent.filter((item) => !item.acknowledged);
  const nextIct = visible.find((item) => item.status !== "Resolved");
  const nextSecurity = unacknowledged[0] ?? urgent[0] ?? visible.find((item) => item.status !== "Resolved");
  const heading = ict ? "ICT work desk" : security ? "Security control desk" : role === "administrator" ? t("readyImpact") : t("howHelp");
  const helper = ict ? "Technology requests assigned to ICT only." : security ? "Security incidents and alerts assigned to your team only." : t(roleSummaryKey[role]);

  return (
    <View style={s.screen}>
      <ServiceHeader section="home" icon={ict ? "computer" : security ? "security" : "space-dashboard"} />
      <ScrollView contentContainerStyle={[s.content, width > 740 && s.wide]} showsVerticalScrollIndicator={false}>
        {student ? <>
          <View style={s.studentHero}>
            <View style={s.heroGlow} />
            <View style={s.studentHeroTop}><View style={s.studentBadge}><MaterialIcons name="school" size={16} color="#9ED2FF" /><Text style={s.studentBadgeText}>CAMPUS CARE</Text></View><View style={s.heroAvatar}><Text style={s.heroAvatarText}>ST</Text></View></View>
            <Text style={s.studentHeroTitle}>Your campus,{"\n"}taken care of.</Text>
            <Text style={s.studentHeroText}>{open.length ? `${open.length} active report${open.length === 1 ? "" : "s"} is being tracked for you.` : "Everything you reported is up to date."}</Text>
            <Pressable onPress={() => { haptic.light(); router.push("/report"); }} style={({ pressed }) => [s.heroCta, pressed && s.pressed]}><View style={s.heroCtaIcon}><MaterialIcons name="add" size={18} color={C.navy} /></View><Text style={s.heroCtaText}>Report a campus issue</Text><MaterialIcons name="arrow-forward" size={18} color={C.navy} /></Pressable>
          </View>
          <View style={s.commandStrip}>
            <StripMetric icon="assignment" value={open.length} label="Active reports" color={C.blue} /><View style={s.stripDivider} /><StripMetric icon="autorenew" value={active.length} label="In progress" color="#6941C6" /><View style={s.stripDivider} /><StripMetric icon="task-alt" value={visible.filter((item) => item.status === "Resolved").length} label="Resolved" color={C.success} />
          </View>
          <View style={s.feedHeader}><View><Text style={s.feedEyebrow}>TRACKING FEED</Text><Text style={s.feedTitle}>Your report activity</Text><Text style={s.feedSub}>Every campus update, in one place.</Text></View><Pressable onPress={() => router.push("/requests")} style={s.allLink}><Text style={s.allLinkText}>View all</Text><MaterialIcons name="arrow-forward" size={14} color={C.blue} /></Pressable></View>
          <View style={s.feed}>{visible.slice(0, 3).map((item) => <StudentReportCard key={item.id} item={item} onPress={() => router.push(`/request/${item.id}`)} />)}</View>
        </> : <>
          <View style={s.intro}><View style={{ flex: 1 }}><Text style={s.eyebrow}>{ict ? "ICT ASSIGNED WORK" : security ? "SECURITY OPERATIONS" : "DEMONSTRATION WORKSPACE"}</Text><Text style={s.title}>{heading}</Text><Text style={s.sub}>{helper}</Text></View>{security && unacknowledged.length > 0 && <View style={s.alertCount}><MaterialIcons name="priority-high" size={18} color={C.danger} /><Text style={s.alertCountText}>{unacknowledged.length}</Text></View>}</View>
          {ict && nextIct ? <TechnicianHero item={nextIct} waiting={waiting.length} onPress={() => router.push(`/request/${nextIct.id}`)} /> : security && nextSecurity ? <SecurityHero item={nextSecurity} pending={unacknowledged.length} onPress={() => router.push(`/request/${nextSecurity.id}`)} /> : <Pressable onPress={() => router.push("/requests")} style={({ pressed }) => [s.standardCta, pressed && s.pressed]}><MaterialIcons name="assignment" size={21} color="#FFF" /><Text style={s.standardCtaText}>{role === "administrator" ? t("reviewRequests") : t("openQueue")}</Text><MaterialIcons name="arrow-forward" size={19} color="#FFF" /></Pressable>}
          <View style={s.staffMetrics}><StaffMetric icon={security ? "warning-amber" : "assignment"} n={security ? urgent.length : open.length} label={security ? "Urgent alerts" : "Assigned work"} color={security ? C.danger : C.blue} /><StaffMetric icon="autorenew" n={active.length} label="In progress" color="#6941C6" /><StaffMetric icon="schedule" n={waiting.length} label={ict ? "Need ICT triage" : security ? "Awaiting action" : t("needRouting")} color={C.warn} /></View>
          <View style={s.feedHeader}><View><Text style={s.feedEyebrow}>{security ? "SECURITY QUEUE" : ict ? "ICT QUEUE" : "OPERATIONS FEED"}</Text><Text style={s.feedTitle}>{security ? "Incidents in view" : ict ? "Technology work" : t("recentActivity")}</Text><Text style={s.feedSub}>{security ? "Only Security assignments." : ict ? "Only ICT assignments." : t("latestVisible")}</Text></View><Pressable onPress={() => router.push("/requests")} style={s.allLink}><Text style={s.allLinkText}>{t("viewAll")}</Text><MaterialIcons name="arrow-forward" size={14} color={C.blue} /></Pressable></View>
          <View style={s.feed}>{visible.slice(0, 4).map((item) => <Card key={item.id} item={item} onPress={() => router.push(`/request/${item.id}`)} />)}</View>
        </>}
      </ScrollView>
    </View>
  );
}

function StripMetric({ icon, value, label, color }: { icon: keyof typeof MaterialIcons.glyphMap; value: number; label: string; color: string }) { return <View style={s.stripMetric}><MaterialIcons name={icon} size={17} color={color} /><Text style={s.stripValue}>{value}</Text><Text style={s.stripLabel}>{label}</Text></View>; }
function StaffMetric({ icon, n, label, color }: { icon: keyof typeof MaterialIcons.glyphMap; n: number; label: string; color: string }) { return <View style={s.staffMetric}><View style={[s.staffMetricIcon, { backgroundColor: `${color}16` }]}><MaterialIcons name={icon} size={18} color={color} /></View><Text style={s.staffMetricValue}>{n}</Text><Text style={s.staffMetricLabel}>{label}</Text></View>; }

function StudentReportCard({ item, onPress }: { item: any; onPress: () => void }) {
  const progress = item.status === "Submitted" ? "Awaiting team review" : item.status === "Assigned" ? "Assigned to the right team" : item.status === "In Progress" ? "Work is in progress" : "Issue resolved";
  const color = item.status === "Resolved" ? C.success : item.status === "In Progress" ? "#6941C6" : item.status === "Assigned" ? C.blue : C.warn;
  const icon = item.category === "ICT" ? "computer" : item.category === "Security" ? "security" : item.category === "Plumbing" ? "water-drop" : "handyman";
  return <Pressable onPress={onPress} style={({ pressed }) => [s.reportCard, pressed && s.pressed]}><View style={[s.reportAccent, { backgroundColor: color }]} /><View style={s.reportHead}><View style={[s.reportIcon, { backgroundColor: `${color}16` }]}><MaterialIcons name={icon as keyof typeof MaterialIcons.glyphMap} size={18} color={color} /></View><View style={{ flex: 1 }}><Text style={s.reportRef}>{item.id}</Text><Text style={s.reportTeam}>{item.team}</Text></View><View style={[s.reportStatus, { backgroundColor: `${color}16` }]}><Text style={[s.reportStatusText, { color }]}>{item.status}</Text></View></View><Text style={s.reportTitle} numberOfLines={2}>{item.title}</Text><View style={s.reportLocation}><MaterialIcons name="location-on" size={14} color={C.muted} /><Text style={s.reportLocationText} numberOfLines={1}>{item.location}</Text></View><View style={s.reportProgress}><View style={s.progressMeta}><Text style={s.progressLabel}>{progress}</Text><Text style={[s.progressPriority, { color }]}>{item.priority}</Text></View><View style={s.progressTrack}><View style={[s.progressFill, { backgroundColor: color, width: item.status === "Submitted" ? "25%" : item.status === "Assigned" ? "48%" : item.status === "In Progress" ? "72%" : "100%" }]} /></View></View><View style={s.reportFoot}><Text style={s.reportTrack}>Open tracking</Text><MaterialIcons name="arrow-forward" size={16} color={C.blue} /></View></Pressable>;
}

function TechnicianHero({ item, waiting, onPress }: { item: any; waiting: number; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.staffHero, pressed && s.pressed]}><View style={s.staffHeroTop}><View style={s.staffHeroBadge}><MaterialIcons name="bolt" size={15} color="#BBD8FF" /><Text style={s.staffHeroBadgeText}>NEXT ICT ASSIGNMENT</Text></View><Text style={s.staffHeroRef}>{item.id}</Text></View><Text style={s.staffHeroTitle}>{item.title}</Text><View style={s.staffHeroLocation}><MaterialIcons name="location-on" size={16} color="#BBD8FF" /><Text style={s.staffHeroLocationText}>{item.location}</Text></View><View style={s.staffHeroFoot}><Text style={s.staffHeroMeta}>{item.status} · {item.priority} priority{"\n"}{waiting} waiting for ICT triage</Text><View style={s.staffHeroAction}><Text style={s.staffHeroActionText}>{item.status === "Assigned" ? "Start work" : "Open job"}</Text><MaterialIcons name="arrow-forward" size={16} color={C.navy} /></View></View></Pressable>; }
function SecurityHero({ item, pending, onPress }: { item: any; pending: number; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.securityHero, pressed && s.pressed]}><View style={s.staffHeroTop}><View style={s.staffHeroBadge}><MaterialIcons name="priority-high" size={15} color="#FFE1DE" /><Text style={s.staffHeroBadgeText}>URGENT SECURITY ALERT</Text></View><Text style={s.staffHeroRef}>{item.id}</Text></View><Text style={s.staffHeroTitle}>{item.title}</Text><View style={s.staffHeroLocation}><MaterialIcons name="location-on" size={16} color="#FFE1DE" /><Text style={s.staffHeroLocationText}>{item.location}</Text></View><View style={s.staffHeroFoot}><Text style={s.staffHeroMeta}>{item.acknowledged ? "Acknowledged incident" : "Acknowledgement required"}{"\n"}{pending} urgent alert{pending === 1 ? "" : "s"} open</Text><View style={[s.staffHeroAction, { backgroundColor: "#FFF4F2" }]}><Text style={[s.staffHeroActionText, { color: C.danger }]}>{item.acknowledged ? "Inspect" : "Respond"}</Text><MaterialIcons name="arrow-forward" size={16} color={C.danger} /></View></View></Pressable>; }

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 36, gap: 18, maxWidth: 780, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, pressed: { opacity: 0.88, transform: [{ scale: 0.99 }] },
  studentHero: { overflow: "hidden", borderRadius: 28, backgroundColor: C.navy, padding: 21, gap: 11, minHeight: 258, ...shadow }, heroGlow: { position: "absolute", width: 250, height: 250, borderRadius: 125, right: -105, top: -100, backgroundColor: "#1C76DB", opacity: 0.72 }, studentHeroTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, studentBadge: { flexDirection: "row", gap: 6, alignItems: "center" }, studentBadgeText: { color: "#BBD8FF", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, heroAvatar: { height: 36, width: 36, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.17)", alignItems: "center", justifyContent: "center" }, heroAvatarText: { color: "#FFF", fontSize: 11, fontWeight: "900" }, studentHeroTitle: { color: "#FFF", fontSize: 31, lineHeight: 37, letterSpacing: -0.6, fontWeight: "900", maxWidth: "84%" }, studentHeroText: { color: "#C7E2FF", fontSize: 13, lineHeight: 19, maxWidth: "76%" }, heroCta: { minHeight: 47, borderRadius: 15, backgroundColor: "#FFF", paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 9, marginTop: "auto" }, heroCtaIcon: { height: 27, width: 27, borderRadius: 9, backgroundColor: C.sky, alignItems: "center", justifyContent: "center" }, heroCtaText: { color: C.navy, fontSize: 13, fontWeight: "900", flex: 1 },
  commandStrip: { marginTop: -30, marginHorizontal: 10, backgroundColor: "#FFF", borderRadius: 18, minHeight: 86, borderWidth: 1, borderColor: C.border, flexDirection: "row", alignItems: "center", paddingHorizontal: 8, ...shadow }, stripMetric: { flex: 1, alignItems: "center", gap: 3 }, stripValue: { color: C.navy, fontSize: 20, fontWeight: "900" }, stripLabel: { color: C.muted, fontSize: 9, fontWeight: "800", textAlign: "center" }, stripDivider: { width: 1, height: 36, backgroundColor: C.border },
  feedHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", gap: 14, marginTop: 4 }, feedEyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.1, fontWeight: "900" }, feedTitle: { color: C.navy, fontSize: 20, lineHeight: 25, fontWeight: "900", marginTop: 3 }, feedSub: { color: C.muted, fontSize: 12, marginTop: 2 }, allLink: { flexDirection: "row", alignItems: "center", gap: 3, padding: 7 }, allLinkText: { color: C.blue, fontSize: 12, fontWeight: "900" }, feed: { gap: 12 },
  reportCard: { position: "relative", backgroundColor: "#FFF", overflow: "hidden", borderRadius: 22, borderWidth: 1, borderColor: C.border, padding: 15, gap: 10, ...shadow }, reportAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 5 }, reportHead: { flexDirection: "row", alignItems: "center", gap: 9 }, reportIcon: { height: 36, width: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" }, reportRef: { color: C.navy, fontSize: 12, fontWeight: "900" }, reportTeam: { color: C.muted, fontSize: 10, fontWeight: "700", marginTop: 1 }, reportStatus: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, reportStatusText: { fontSize: 10, fontWeight: "900" }, reportTitle: { color: C.navy, fontSize: 16, lineHeight: 21, fontWeight: "900" }, reportLocation: { flexDirection: "row", alignItems: "center", gap: 3 }, reportLocationText: { color: C.muted, fontSize: 12, flex: 1 }, reportProgress: { gap: 5, marginTop: 1 }, progressMeta: { flexDirection: "row", justifyContent: "space-between" }, progressLabel: { color: C.muted, fontSize: 10, fontWeight: "800" }, progressPriority: { fontSize: 10, fontWeight: "900" }, progressTrack: { height: 5, borderRadius: 4, backgroundColor: "#E6ECF3", overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 4 }, reportFoot: { borderTopWidth: 1, borderTopColor: C.border, paddingTop: 9, marginTop: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, reportTrack: { color: C.blue, fontSize: 11, fontWeight: "900" },
  intro: { flexDirection: "row", gap: 14, alignItems: "flex-start" }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.2, fontWeight: "900", marginBottom: 6 }, title: { color: C.navy, fontSize: 29, lineHeight: 35, letterSpacing: -0.5, fontWeight: "900" }, sub: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 5 }, alertCount: { flexDirection: "row", gap: 3, backgroundColor: "#FDECEC", borderRadius: 14, paddingHorizontal: 10, paddingVertical: 9 }, alertCountText: { color: C.danger, fontWeight: "900" }, standardCta: { minHeight: 56, borderRadius: 18, backgroundColor: C.navy, paddingHorizontal: 17, flexDirection: "row", alignItems: "center", gap: 10, ...shadow }, standardCtaText: { flex: 1, color: "#FFF", fontSize: 16, fontWeight: "900" },
  staffHero: { backgroundColor: C.navy, borderRadius: 23, padding: 18, gap: 10, ...shadow }, securityHero: { backgroundColor: "#761D19", borderRadius: 23, padding: 18, gap: 10, shadowColor: "#7A271A", shadowOpacity: 0.18, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, staffHeroTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, staffHeroBadge: { flexDirection: "row", alignItems: "center", gap: 5 }, staffHeroBadgeText: { color: "#BBD8FF", fontSize: 10, letterSpacing: 1, fontWeight: "900" }, staffHeroRef: { color: "#FFF", fontSize: 11, fontWeight: "900" }, staffHeroTitle: { color: "#FFF", fontSize: 21, lineHeight: 27, fontWeight: "900" }, staffHeroLocation: { flexDirection: "row", alignItems: "center", gap: 4 }, staffHeroLocationText: { color: "#D7E8FF", fontSize: 12, fontWeight: "700", flex: 1 }, staffHeroFoot: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", gap: 12, paddingTop: 12, marginTop: 2, borderTopColor: "rgba(255,255,255,0.18)", borderTopWidth: 1 }, staffHeroMeta: { color: "#BBD8FF", fontSize: 10, lineHeight: 15, fontWeight: "700" }, staffHeroAction: { minHeight: 34, paddingHorizontal: 10, borderRadius: 11, backgroundColor: "#FFF", flexDirection: "row", alignItems: "center", gap: 4 }, staffHeroActionText: { color: C.navy, fontSize: 11, fontWeight: "900" },
  staffMetrics: { flexDirection: "row", gap: 10 }, staffMetric: { flex: 1, minHeight: 104, backgroundColor: "#FFF", borderRadius: 18, borderWidth: 1, borderColor: C.border, padding: 13, gap: 6 }, staffMetricIcon: { height: 33, width: 33, borderRadius: 11, alignItems: "center", justifyContent: "center" }, staffMetricValue: { color: C.navy, fontSize: 22, fontWeight: "900" }, staffMetricLabel: { color: C.muted, fontSize: 11, lineHeight: 14, fontWeight: "700" },
});
