import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Mark } from "@/components/campus-ui";
import { LanguagePicker } from "@/components/language-picker";
import { C } from "@/constants/campus";
import { roleLabelKey, useI18n } from "@/lib/i18n";
import { roles, useMaintenance } from "@/lib/maintenance-store";
const useRouter = () => useExpoRouter() as any;
export default function Profile() { const router = useRouter(); const { role } = useMaintenance(); const { t } = useI18n(); const { width } = useWindowDimensions(); const r = roles[role]; return <View style={s.screen}><ScrollView contentContainerStyle={[s.content, width > 740 && s.wide]}><Mark /><View style={s.hero}><View style={s.initials}><Text style={s.initialsText}>{r.initials}</Text></View><View><Text style={s.name}>{r.name}</Text><Text style={s.role}>{t(roleLabelKey[role])}</Text><Text style={s.demo}>{t("demoWorkspace")}</Text></View></View><Text style={s.section}>{t("language")}</Text><LanguagePicker /><Text style={s.section}>{t("workspace")}</Text><View style={s.list}><Row icon="switch-account" title={t("switchRole")} detail={t("rolePreviewIntro")} onPress={() => router.push("/role-select")} /><Row icon="notifications-none" title={t("notifications")} detail={t("activityTimelineIntro")} onPress={() => {}} /><Row icon="help-outline" title={t("helpSupport")} detail={t("securityNote")} onPress={() => {}} /></View><View style={s.notice}><MaterialIcons name="info-outline" size={19} color={C.blue} /><Text style={s.noticeText}>{t("profileDemoNote")}</Text></View></ScrollView></View>; }
function Row({ icon, title, detail, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; onPress: () => void }) { return <Pressable onPress={onPress} style={s.row}><View style={s.rowIcon}><MaterialIcons name={icon} size={20} color={C.blue} /></View><View style={{ flex: 1 }}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail} numberOfLines={2}>{detail}</Text></View><MaterialIcons name="chevron-right" size={22} color={C.muted} /></Pressable>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 34, gap: 18, maxWidth: 780, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, hero: { backgroundColor: C.navy, borderRadius: 22, padding: 20, flexDirection: "row", alignItems: "center", gap: 14 }, initials: { width: 52, height: 52, borderRadius: 18, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, initialsText: { color: C.navy, fontWeight: "900", fontSize: 16 }, name: { color: "#FFF", fontSize: 19, fontWeight: "900" }, role: { color: "#BBD8FF", fontSize: 13, fontWeight: "700", marginTop: 2 }, demo: { color: "#7FC0FF", fontSize: 9, letterSpacing: 1, fontWeight: "900", marginTop: 4 }, section: { color: C.navy, fontSize: 17, fontWeight: "900" }, list: { overflow: "hidden", borderRadius: 20, borderColor: C.border, borderWidth: 1, backgroundColor: C.surface }, row: { minHeight: 76, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: C.border }, rowIcon: { height: 37, width: 37, borderRadius: 12, backgroundColor: C.sky, alignItems: "center", justifyContent: "center" }, rowTitle: { color: C.navy, fontSize: 14, fontWeight: "900" }, rowDetail: { color: C.muted, fontSize: 12, marginTop: 2 }, notice: { flexDirection: "row", gap: 9, alignItems: "flex-start", padding: 14, borderRadius: 17, backgroundColor: C.sky, borderWidth: 1, borderColor: "#CFE4FC" }, noticeText: { color: "#31547F", fontSize: 12, lineHeight: 18, flex: 1, fontWeight: "600" } });
