import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Card } from "@/components/campus-ui";
import { C } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { roleLabelKey, useI18n } from "@/lib/i18n";
import { type Team, useMaintenance } from "@/lib/maintenance-store";
import { filterAndSortRequests } from "@/lib/request-queue";

const useRouter = () => useExpoRouter() as any;
type StatusFilter = "All" | "Submitted" | "Assigned" | "In Progress" | "Resolved";
type PriorityFilter = "All" | "Urgent" | "High" | "Medium" | "Low";
type TeamFilter = "All" | Team;
type Sort = "Newest" | "Oldest" | "Priority" | "Pending";
const statusOptions: StatusFilter[] = ["All", "Submitted", "Assigned", "In Progress", "Resolved"];
const priorityOptions: PriorityFilter[] = ["All", "Urgent", "High", "Medium", "Low"];
const teamOptions: TeamFilter[] = ["All", "ICT", "Physical Maintenance", "Security"];
const sortOptions: Sort[] = ["Newest", "Priority", "Pending", "Oldest"];

export default function Requests() {
  const router = useRouter(); const { width } = useWindowDimensions(); const { role, visible, requests } = useMaintenance(); const { t } = useI18n(); const admin = role === "administrator";
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("All"); const [priorityFilter, setPriorityFilter] = useState<PriorityFilter>("All"); const [teamFilter, setTeamFilter] = useState<TeamFilter>("All"); const [sort, setSort] = useState<Sort>("Newest");
  const data = useMemo(() => {
    return admin ? filterAndSortRequests(requests, { status: statusFilter, priority: priorityFilter, team: teamFilter, sort }) : visible;
  }, [admin, priorityFilter, requests, sort, statusFilter, teamFilter, visible]);
  const label = (value: string) => value === "All" ? t("all") : value === "Submitted" ? t("submitted") : value === "Assigned" ? t("assigned") : value === "In Progress" ? t("inProgress") : value === "Resolved" ? t("resolved") : value === "Urgent" ? t("urgent") : value === "High" ? t("high") : value === "Medium" ? t("medium") : value === "Low" ? t("low") : value === "ICT" ? t("ict") : value === "Physical Maintenance" ? t("physicalMaintenance") : value === "Security" ? t("security") : value;
  const queueLens = `Status: ${label(statusFilter)} · Priority: ${label(priorityFilter)} · Team: ${label(teamFilter)} · Sort: ${sort}`;
  const ChipGroup = ({ title, items, selected, setSelected }: { title: string; items: string[]; selected: string; setSelected: (value: any) => void }) => <View style={s.filterGroup}><Text style={s.filterTitle}>{title}</Text><View style={s.chips}>{items.map((item) => <Pressable key={item} onPress={() => { haptic.light(); setSelected(item); }} style={[s.chip, selected === item && s.chipOn]}><Text style={[s.chipText, selected === item && s.chipTextOn]}>{label(item)}</Text></Pressable>)}</View></View>;
  return <View style={s.screen}><FlatList data={data} keyExtractor={(item) => item.id} contentContainerStyle={[s.content, width > 740 && s.wide]} ItemSeparatorComponent={() => <View style={{ height: 12 }} />} ListHeaderComponent={<View><View style={s.header}><View style={{ flex: 1 }}><Text style={s.eyebrow}>{admin ? "ADMINISTRATOR CONTROL" : t(roleLabelKey[role]).toUpperCase()}</Text><Text style={s.title}>{admin ? t("requestCommand") : role === "student" ? t("myRequests") : t("myQueue")}</Text><Text style={s.sub}>{admin ? "Filter urgent, pending, and team-specific work across the campus." : role === "student" ? t("myRequestIntro") : t("myQueueIntro")}</Text></View>{role === "student" && <Pressable onPress={() => router.push("/report")} style={s.add} accessibilityLabel={t("reportIssue")}><MaterialIcons name="add" size={20} color="#FFF" /></Pressable>}</View>{admin && <><View style={s.queueLens}><View style={s.queueLensIcon}><MaterialIcons name="visibility" size={18} color={C.blue} /></View><View style={{ flex: 1 }}><Text style={s.queueLensTitle}>Queue lens</Text><Text style={s.queueLensText}>{queueLens}</Text></View><View style={s.queueLensCount}><Text style={s.queueLensCountText}>{data.length}</Text></View></View><View style={s.controls}><View style={s.controlsTop}><View><Text style={s.controlsTitle}>Queue controls</Text><Text style={s.count}>{data.length} matching request{data.length === 1 ? "" : "s"}</Text></View><View style={s.sortIcon}><MaterialIcons name="sort" size={20} color={C.blue} /></View></View><ChipGroup title="Status" items={statusOptions} selected={statusFilter} setSelected={setStatusFilter} /><ChipGroup title="Priority" items={priorityOptions} selected={priorityFilter} setSelected={setPriorityFilter} /><ChipGroup title="Team" items={teamOptions} selected={teamFilter} setSelected={setTeamFilter} /><ChipGroup title="Sort by" items={sortOptions} selected={sort} setSelected={setSort} /></View></>}</View>} ListHeaderComponentStyle={{ marginBottom: 18 }} renderItem={({ item }) => <Card item={item} onPress={() => router.push(`/request/${item.id}`)} />} ListEmptyComponent={<View style={s.empty}><MaterialIcons name="filter-alt-off" size={27} color={C.muted} /><Text style={s.emptyText}>{admin ? "No requests match the current controls." : t("noRequests")}</Text></View>} ListFooterComponent={<View style={{ height: 22 }} />} /></View>;
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 36, maxWidth: 780, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, header: { flexDirection: "row", gap: 12 }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.2, fontWeight: "900", marginBottom: 6 }, title: { color: C.navy, fontSize: 27, lineHeight: 32, fontWeight: "900" }, sub: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 5 }, add: { backgroundColor: C.navy, height: 42, width: 42, borderRadius: 14, justifyContent: "center", alignItems: "center" },
  queueLens: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 18, borderWidth: 1, borderColor: "#CFE4FC", backgroundColor: C.sky, padding: 13, marginTop: 18 }, queueLensIcon: { height: 36, width: 36, borderRadius: 12, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, queueLensTitle: { color: C.navy, fontSize: 13, fontWeight: "900" }, queueLensText: { color: "#31547F", fontSize: 11, lineHeight: 16, marginTop: 2 }, queueLensCount: { minHeight: 32, minWidth: 32, borderRadius: 16, backgroundColor: C.navy, alignItems: "center", justifyContent: "center", paddingHorizontal: 7 }, queueLensCountText: { color: "#FFF", fontSize: 12, fontWeight: "900" }, controls: { backgroundColor: C.surface, borderRadius: 20, borderWidth: 1, borderColor: C.border, padding: 15, gap: 13, marginTop: 10 }, controlsTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, controlsTitle: { color: C.navy, fontSize: 15, fontWeight: "900" }, count: { color: C.muted, fontSize: 11, marginTop: 2, fontWeight: "700" }, sortIcon: { height: 35, width: 35, borderRadius: 11, backgroundColor: C.sky, justifyContent: "center", alignItems: "center" }, filterGroup: { gap: 7 }, filterTitle: { color: C.muted, fontSize: 10, letterSpacing: 0.8, fontWeight: "900" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { minHeight: 33, paddingHorizontal: 10, justifyContent: "center", borderRadius: 10, backgroundColor: C.bg, borderColor: C.border, borderWidth: 1 }, chipOn: { backgroundColor: C.navy, borderColor: C.navy }, chipText: { color: C.muted, fontSize: 11, fontWeight: "900" }, chipTextOn: { color: "#FFF" },
  empty: { padding: 30, borderRadius: 18, backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, alignItems: "center", gap: 8 }, emptyText: { color: C.muted, fontSize: 13, textAlign: "center" },
});
