import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter as useExpoRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Card } from "@/components/campus-ui";
import { C } from "@/constants/campus";
import { haptic } from "@/lib/haptics";
import { roles, type Team, useMaintenance } from "@/lib/maintenance-store";

const useRouter = () => useExpoRouter() as any;
type Filter = "All" | "Unassigned" | Team;
export default function Requests() { const router = useRouter(); const { width } = useWindowDimensions(); const { role, visible, requests } = useMaintenance(); const [filter, setFilter] = useState<Filter>("All"); const admin = role === "administrator"; const data = useMemo(() => !admin || filter === "All" ? visible : filter === "Unassigned" ? requests.filter((r) => r.status === "Submitted") : requests.filter((r) => r.team === filter), [admin, filter, requests, visible]); const filters: Filter[] = ["All", "Unassigned", "ICT", "Physical Maintenance", "Security"];
 return <View style={s.screen}><FlatList data={data} keyExtractor={(x) => x.id} contentContainerStyle={[s.content, width > 740 && s.wide]} ItemSeparatorComponent={() => <View style={{ height: 12 }} />} ListHeaderComponent={<View style={s.header}><View style={{ flex: 1 }}><Text style={s.eyebrow}>{admin ? "CAMPUS-WIDE WORK" : roles[role].label.toUpperCase()}</Text><Text style={s.title}>{admin ? "Request command center" : role === "student" ? "My requests" : "My work queue"}</Text><Text style={s.sub}>{admin ? "Review priorities and route every request to the right team." : role === "student" ? "Track every issue you have reported." : "Open a request to record progress or resolve work."}</Text></View>{role === "student" && <Pressable onPress={() => router.push("/report")} style={s.add}><MaterialIcons name="add" size={20} color="#FFF" /></Pressable>}</View>} ListHeaderComponentStyle={{ marginBottom: 18 }} renderItem={({ item }) => <Card item={item} onPress={() => router.push(`/request/${item.id}`)} />} ListEmptyComponent={<View style={s.empty}><Text style={s.emptyText}>Nothing in this queue yet.</Text></View>} ListFooterComponent={<View style={{ height: admin ? 75 : 18 }} />} />{admin && <View style={s.rail}>{filters.map((v) => <Pressable key={v} onPress={() => { haptic.light(); setFilter(v); }} style={[s.filter, v === filter && s.selected]}><Text style={[s.filterText, v === filter && s.selectedText]}>{v}</Text></Pressable>)}</View>}</View>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 92, maxWidth: 780, width: "100%", alignSelf: "center" }, wide: { paddingHorizontal: 28, paddingTop: 28 }, header: { flexDirection: "row", gap: 12 }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.2, fontWeight: "900", marginBottom: 6 }, title: { color: C.navy, fontSize: 27, lineHeight: 32, fontWeight: "900" }, sub: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 5 }, add: { backgroundColor: C.navy, height: 42, width: 42, borderRadius: 14, justifyContent: "center", alignItems: "center" }, rail: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 10, gap: 8, flexDirection: "row", backgroundColor: "rgba(246,248,252,0.98)", borderTopColor: C.border, borderTopWidth: 1 }, filter: { minHeight: 37, paddingHorizontal: 12, borderRadius: 99, justifyContent: "center", backgroundColor: C.surface, borderColor: C.border, borderWidth: 1 }, selected: { backgroundColor: C.navy, borderColor: C.navy }, filterText: { color: C.muted, fontSize: 11, fontWeight: "900" }, selectedText: { color: "#FFF" }, empty: { padding: 30, borderRadius: 18, backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, alignItems: "center" }, emptyText: { color: C.muted, fontSize: 13 } });
