import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { C, shadow } from "@/constants/campus";

type Preference = { key: "assignments" | "arrivals" | "urgent" | "resolutions"; icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; value: boolean };
const initial: Preference[] = [{ key: "assignments", icon: "assignment", title: "New assignments", detail: "When a request is assigned to your team.", value: true }, { key: "arrivals", icon: "schedule", title: "Technician arrival times", detail: "When a technician adds or changes an ETA.", value: true }, { key: "urgent", icon: "priority-high", title: "Urgent and security alerts", detail: "Immediate alerts for priority campus incidents.", value: true }, { key: "resolutions", icon: "task-alt", title: "Resolved requests", detail: "When reported work is completed.", value: true }];

export default function NotificationSettings() { const router = useRouter(); const [preferences, setPreferences] = useState(initial); const toggle = (key: Preference["key"]) => setPreferences((all) => all.map((item) => item.key === key ? { ...item, value: !item.value } : item)); return <View style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.navy} /></Pressable><View><Text style={s.eyebrow}>PREFERENCES</Text><Text style={s.title}>Notifications</Text></View></View><View style={s.hero}><View style={s.heroIcon}><MaterialIcons name="notifications-active" size={22} color="#FFF" /></View><View style={{ flex: 1 }}><Text style={s.heroTitle}>Stay in the loop.</Text><Text style={s.heroText}>Choose the operational updates that should reach your Campus Maintenance workspace.</Text></View></View><Text style={s.section}>Request updates</Text><View style={s.list}>{preferences.map((item, index) => <View key={item.key} style={[s.row, index === preferences.length - 1 && s.lastRow]}><View style={[s.rowIcon, item.key === "urgent" && s.urgentIcon]}><MaterialIcons name={item.icon} size={19} color={item.key === "urgent" ? C.danger : C.blue} /></View><View style={{ flex: 1 }}><Text style={s.rowTitle}>{item.title}</Text><Text style={s.rowDetail}>{item.detail}</Text></View><Switch value={item.value} onValueChange={() => toggle(item.key)} trackColor={{ false: "#C8D2E0", true: "#8EC5FF" }} thumbColor={item.value ? C.blue : "#FFF"} /></View>)}</View><View style={s.note}><MaterialIcons name="info-outline" size={18} color={C.blue} /><Text style={s.noteText}>Urgent security alerts are enabled by default to support a timely campus response. Android notification delivery is ready when the signed-in production account is connected.</Text></View></ScrollView></View>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 38, gap: 17, maxWidth: 700, width: "100%", alignSelf: "center" }, top: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFF", borderWidth: 1, borderColor: C.border, alignItems: "center", justifyContent: "center" }, eyebrow: { color: C.blue, fontSize: 10, letterSpacing: 1.1, fontWeight: "900" }, title: { color: C.navy, fontSize: 24, lineHeight: 29, fontWeight: "900" }, hero: { backgroundColor: C.navy, borderRadius: 22, padding: 17, flexDirection: "row", gap: 12, alignItems: "center", ...shadow }, heroIcon: { width: 45, height: 45, borderRadius: 15, backgroundColor: "rgba(255,255,255,0.16)", justifyContent: "center", alignItems: "center" }, heroTitle: { color: "#FFF", fontSize: 17, fontWeight: "900" }, heroText: { color: "#C7E2FF", fontSize: 12, lineHeight: 17, marginTop: 3 }, section: { color: C.navy, fontSize: 16, fontWeight: "900", marginTop: 3 }, list: { backgroundColor: "#FFF", borderRadius: 20, borderWidth: 1, borderColor: C.border, overflow: "hidden" }, row: { minHeight: 83, padding: 14, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: 1, borderBottomColor: C.border }, lastRow: { borderBottomWidth: 0 }, rowIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: C.sky, alignItems: "center", justifyContent: "center" }, urgentIcon: { backgroundColor: "#FDECEC" }, rowTitle: { color: C.navy, fontSize: 13, fontWeight: "900" }, rowDetail: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 2 }, note: { flexDirection: "row", alignItems: "flex-start", gap: 8, backgroundColor: C.sky, borderRadius: 15, borderWidth: 1, borderColor: "#CFE4FC", padding: 12 }, noteText: { flex: 1, color: "#31547F", fontSize: 11, lineHeight: 17, fontWeight: "600" } });
